/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WidgetPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/utils.ts
function generateId() {
  const d = new Date();
  const pad = (n, len = 2) => String(n).padStart(len, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;
}

// src/store/WidgetStore.ts
var WidgetStore = class {
  constructor(loadData, saveData) {
    this.data = { widgets: [] };
    this.saveFn = async () => {
      await saveData(this.data);
    };
    this.init(loadData);
  }
  async init(loadData) {
    const loaded = await loadData();
    if (loaded && loaded.widgets) {
      this.data = loaded;
    }
  }
  getWidgets() {
    return this.data.widgets;
  }
  getWidget(id) {
    return this.data.widgets.find((w) => w.id === id);
  }
  async addWidget(def) {
    const widget = {
      ...def,
      id: generateId(),
      createdAt: Date.now(),
      updatedAt: Date.now()
    };
    this.data.widgets.push(widget);
    await this.saveFn();
    return widget;
  }
  async updateWidget(id, updates) {
    const idx = this.data.widgets.findIndex((w) => w.id === id);
    if (idx === -1)
      return false;
    this.data.widgets[idx] = {
      ...this.data.widgets[idx],
      ...updates,
      updatedAt: Date.now()
    };
    await this.saveFn();
    return true;
  }
  async deleteWidget(id) {
    const idx = this.data.widgets.findIndex((w) => w.id === id);
    if (idx === -1)
      return false;
    this.data.widgets.splice(idx, 1);
    await this.saveFn();
    return true;
  }
  async importWidgets(defs) {
    const now = Date.now();
    for (const def of defs) {
      if (!this.getWidget(def.id)) {
        this.data.widgets.push({
          ...def,
          createdAt: now,
          updatedAt: now
        });
      }
    }
    await this.saveFn();
    return defs.length;
  }
  exportWidgets() {
    return JSON.parse(JSON.stringify(this.data.widgets));
  }
};

// src/widgets/registry.ts
var widgetMap = /* @__PURE__ */ new Map();
var metaMap = /* @__PURE__ */ new Map();
function registerWidgetType(ctor, meta) {
  widgetMap.set(meta.type, ctor);
  metaMap.set(meta.type, meta);
}
function createWidget(type) {
  const Ctor = widgetMap.get(type);
  if (!Ctor)
    return null;
  return new Ctor();
}
function getWidgetMeta(type) {
  return metaMap.get(type);
}
function getAllWidgetMetas() {
  return Array.from(metaMap.values());
}
function getAllWidgetTypes() {
  return Array.from(metaMap.keys());
}

// src/widgets/base.ts
var BaseWidget = class {
  constructor() {
    this.container = null;
    this.config = null;
  }
  async render(container, config) {
    this.container = container;
    this.config = config;
    container.empty();
    await this.renderContent(container, config);
  }
  async refresh() {
    if (this.container && this.config) {
      await this.render(this.container, this.config);
    }
  }
  destroy() {
    this.container = null;
    this.config = null;
  }
};

// src/i18n.ts
var currentLang = "zh";
var translations = {
  "plugin-name": { en: "xiaoyuanWidget", zh: "\u5C0F\u5143\u6302\u4EF6" },
  "plugin-desc": { en: "Modular widgets \u2014 stats, Dataview queries, tag cloud and more", zh: "\u6A21\u5757\u5316\u6302\u4EF6 \u2014 \u7EDF\u8BA1\u3001Dataview \u67E5\u8BE2\u3001\u6807\u7B7E\u4E91\u7B49" },
  "settings-general": { en: "General Settings", zh: "\u901A\u7528\u8BBE\u7F6E" },
  "settings-widget-mgr": { en: "Widget Manager", zh: "\u6302\u4EF6\u7BA1\u7406" },
  "settings-dataview": { en: "Dataview Integration", zh: "Dataview \u96C6\u6210" },
  "btn-new-widget": { en: "New Widget", zh: "\u65B0\u5EFA\u6302\u4EF6" },
  "btn-edit": { en: "Edit", zh: "\u7F16\u8F91" },
  "btn-delete": { en: "Delete", zh: "\u5220\u9664" },
  "btn-save": { en: "Save", zh: "\u4FDD\u5B58" },
  "btn-cancel": { en: "Cancel", zh: "\u53D6\u6D88" },
  "btn-insert": { en: "Insert", zh: "\u63D2\u5165" },
  "btn-export": { en: "Export", zh: "\u5BFC\u51FA" },
  "btn-import": { en: "Import", zh: "\u5BFC\u5165" },
  "btn-import-all": { en: "Import All", zh: "\u5168\u90E8\u5BFC\u5165" },
  "label-name": { en: "Name", zh: "\u540D\u79F0" },
  "label-id": { en: "ID", zh: "ID" },
  "label-type": { en: "Type", zh: "\u7C7B\u578B" },
  "label-config": { en: "Configuration", zh: "\u914D\u7F6E" },
  "label-usage-count": { en: "Usage Count", zh: "\u4F7F\u7528\u6B21\u6570" },
  "label-created": { en: "Created", zh: "\u521B\u5EFA\u65F6\u95F4" },
  "label-updated": { en: "Updated", zh: "\u66F4\u65B0\u65F6\u95F4" },
  "label-no-widgets": { en: 'No widgets yet. Click "New Widget" to create one.', zh: '\u6682\u65E0\u6302\u4EF6\uFF0C\u70B9\u51FB"\u65B0\u5EFA\u6302\u4EF6"\u521B\u5EFA\u7B2C\u4E00\u4E2A\u3002' },
  "label-widget-id": { en: "Widget ID", zh: "\u6302\u4EF6 ID" },
  "label-select-widget": { en: "Select a widget", zh: "\u9009\u62E9\u4E00\u4E2A\u6302\u4EF6" },
  "label-find-references": { en: "Find References", zh: "\u67E5\u627E\u5F15\u7528" },
  "title-edit-widget": { en: "Edit Widget", zh: "\u7F16\u8F91\u6302\u4EF6" },
  "title-new-widget": { en: "New Widget", zh: "\u65B0\u5EFA\u6302\u4EF6" },
  "title-pick-widget": { en: "Insert xiaoyuanWidget", zh: "\u63D2\u5165\u5C0F\u5143\u6302\u4EF6" },
  "title-widget-preview": { en: "Preview", zh: "\u9884\u89C8" },
  "msg-confirm-delete": { en: 'Are you sure you want to delete "{name}"?', zh: '\u786E\u5B9A\u5220\u9664\u6302\u4EF6"{name}"\u5417\uFF1F' },
  "msg-widget-exists": { en: "A widget with this ID already exists.", zh: "\u6B64 ID \u5DF2\u5B58\u5728\u3002" },
  "msg-require-dataview": { en: "Dataview plugin is required. Install and enable it first.", zh: "\u9700\u8981 Dataview \u63D2\u4EF6\uFF0C\u8BF7\u5148\u5B89\u88C5\u5E76\u542F\u7528\u3002" },
  "msg-dataview-query-error": { en: "Query error: {msg}", zh: "\u67E5\u8BE2\u9519\u8BEF\uFF1A{msg}" },
  "msg-no-data": { en: "No data.", zh: "\u6682\u65E0\u6570\u636E\u3002" },
  "msg-import-success": { en: "Imported {n} widget(s).", zh: "\u5DF2\u5BFC\u5165 {n} \u4E2A\u6302\u4EF6\u3002" },
  "msg-copied": { en: "Copied to clipboard!", zh: "\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F\uFF01" },
  "type-stats-card": { en: "Stats Card", zh: "\u7EDF\u8BA1\u5361\u7247" },
  "type-recent-files": { en: "Recent Files", zh: "\u6700\u8FD1\u6587\u4EF6" },
  "type-tag-cloud": { en: "Tag Cloud", zh: "\u6807\u7B7E\u4E91" },
  "type-dv-table": { en: "Dataview Table", zh: "Dataview \u8868\u683C" },
  "type-dv-list": { en: "Dataview List", zh: "Dataview \u5217\u8868" },
  "type-container-row": { en: "Row", zh: "\u884C\u6392\u5217" },
  "type-container-col": { en: "Column", zh: "\u5217\u6392\u5217" },
  "type-container-tab-h": { en: "Horizontal Tabs", zh: "\u6807\u7B7E\u6C34\u5E73\u6392\u5217" },
  "type-container-tab-v": { en: "Vertical Tabs", zh: "\u6807\u7B7E\u5782\u76F4\u6392\u5217" },
  "stats-total-notes": { en: "Total Notes", zh: "\u7B14\u8BB0\u603B\u6570" },
  "stats-today": { en: "Created Today", zh: "\u4ECA\u65E5\u65B0\u5EFA" },
  "stats-week": { en: "This Week", zh: "\u672C\u5468\u65B0\u5EFA" },
  "config-dimension": { en: "Dimension", zh: "\u7EDF\u8BA1\u7EF4\u5EA6" },
  "config-limit": { en: "Max Items", zh: "\u6700\u5927\u6761\u6570" },
  "config-exclude-folders": { en: "Exclude Folders", zh: "\u6392\u9664\u76EE\u5F55" },
  "config-min-count": { en: "Min Count", zh: "\u6700\u5C11\u51FA\u73B0\u6B21\u6570" },
  "config-query": { en: "DQL Query", zh: "DQL \u67E5\u8BE2\u8BED\u53E5" },
  "label-children": { en: "Children", zh: "\u5B50\u6302\u4EF6" },
  "btn-add-child": { en: "Add Child", zh: "\u6DFB\u52A0\u5B50\u6302\u4EF6" },
  "btn-switch-type-warn": { en: "Switching to a non-container type will clear all children. Continue?", zh: "\u5207\u6362\u4E3A\u975E\u5BB9\u5668\u7C7B\u578B\u5C06\u6E05\u9664\u6240\u6709\u5B50\u6302\u4EF6\uFF0C\u662F\u5426\u7EE7\u7EED\uFF1F" },
  "msg-no-children": { en: 'No children. Click "Add Child" to add one.', zh: '\u6682\u65E0\u5B50\u6302\u4EF6\uFF0C\u70B9\u51FB"\u6DFB\u52A0\u5B50\u6302\u4EF6"\u6DFB\u52A0\u3002' },
  "context-insert-widget": { en: "xiaoyuanWidget", zh: "\u5C0F\u5143\u6302\u4EF6" },
  "context-new-widget": { en: "New Widget", zh: "\u65B0\u5EFA" },
  "context-insert-wgt": { en: "Insert Widget", zh: "\u63D2\u5165" },
  "codeblock-hint": { en: "Right-click to insert a widget, or manually write:\n```xiaoyuanwidget\nid: your-widget-id\n```", zh: "\u53F3\u952E\u53EF\u63D2\u5165\u6302\u4EF6\uFF0C\u6216\u624B\u52A8\u7F16\u5199\uFF1A\n```xiaoyuanwidget\nid: your-widget-id\n```" }
};
function getLang() {
  const locale = window.moment?.locale?.() ?? "en";
  return locale.startsWith("zh") ? "zh" : "en";
}
function setLang(lang) {
  currentLang = lang;
}
function t(key, lang) {
  const l = lang ?? currentLang;
  return translations[key]?.[l] ?? key;
}
function t2(key, vars, lang) {
  const l = lang ?? currentLang;
  const str = translations[key]?.[l] ?? key;
  return str.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}

// src/widgets/built-in/StatsCard.ts
var StatsCardWidget = class extends BaseWidget {
  getType() {
    return "stats-card";
  }
  async renderContent(container, config) {
    const app = window.app;
    if (!app)
      return;
    const vault = app.vault;
    const files = vault.getMarkdownFiles();
    const dimension = config.settings.dimension ?? "total";
    let value;
    let label;
    switch (dimension) {
      case "today": {
        const today = new Date();
        const todayStr = today.toISOString().slice(0, 10);
        value = files.filter((f) => {
          const ctime = new Date(f.stat.ctime);
          return ctime.toISOString().slice(0, 10) === todayStr;
        }).length;
        label = t("stats-today");
        break;
      }
      case "week": {
        const weekAgo = Date.now() - 7 * 24 * 60 * 60 * 1e3;
        value = files.filter((f) => f.stat.ctime > weekAgo).length;
        label = t("stats-week");
        break;
      }
      default: {
        value = files.length;
        label = t("stats-total-notes");
        break;
      }
    }
    const title = config.title || label;
    container.addClass("xyw-stats-card");
    container.createEl("div", { cls: "xyw-card-title", text: title });
    const valEl = container.createEl("div", { cls: "xyw-card-value", text: String(value) });
    container.createEl("div", { cls: "xyw-card-label", text: label });
  }
};

// src/widgets/built-in/RecentFiles.ts
var RecentFilesWidget = class extends BaseWidget {
  getType() {
    return "recent-files";
  }
  async renderContent(container, config) {
    const app = window.app;
    if (!app)
      return;
    const vault = app.vault;
    const limit = config.settings.limit ?? 10;
    const excludeFolders = config.settings.excludeFolders ?? [];
    let files = vault.getMarkdownFiles();
    files = files.filter((f) => {
      if (!excludeFolders.length)
        return true;
      return !excludeFolders.some((folder) => f.path.startsWith(folder));
    }).sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, limit);
    container.addClass("xyw-recent-files");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-recent-files") });
    if (!files.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    const list = container.createEl("ul", { cls: "xyw-file-list" });
    for (const file of files) {
      const item = list.createEl("li", { cls: "xyw-file-item" });
      item.textContent = file.name;
      item.setAttr("data-path", file.path);
      item.addEventListener("click", () => {
        app.workspace.getLeaf(false).openFile(file);
      });
    }
  }
};

// src/widgets/built-in/TagCloud.ts
var TagCloudWidget = class extends BaseWidget {
  getType() {
    return "tag-cloud";
  }
  async renderContent(container, config) {
    const app = window.app;
    if (!app)
      return;
    const vault = app.vault;
    const minCount = config.settings.minCount ?? 1;
    const tagCount = /* @__PURE__ */ new Map();
    const files = vault.getMarkdownFiles();
    const cache = app.metadataCache;
    for (const file of files) {
      const metadata = cache.getFileCache(file);
      if (!metadata?.frontmatter?.tags)
        continue;
      const tags = metadata.frontmatter.tags;
      const tagArr = Array.isArray(tags) ? tags : [tags];
      for (const tag of tagArr) {
        const cleanTag = String(tag).replace(/^#/, "");
        tagCount.set(cleanTag, (tagCount.get(cleanTag) ?? 0) + 1);
      }
    }
    const sorted = Array.from(tagCount.entries()).filter(([_, count]) => count >= minCount).sort((a, b) => b[1] - a[1]);
    container.addClass("xyw-tag-cloud");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-tag-cloud") });
    if (!sorted.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    const maxCount = sorted[0][1];
    const wrapper = container.createEl("div", { cls: "xyw-tags-wrapper" });
    for (const [tag, count] of sorted) {
      const size = 0.8 + count / maxCount * 1.2;
      const el = wrapper.createEl("span", {
        cls: "xyw-tag-item",
        text: `#${tag}`
      });
      el.style.fontSize = `${size}em`;
      el.setAttr("title", `${tag} (${count})`);
      el.addEventListener("click", () => {
        window.app.internalPlugins.getPluginById("global-search")?.instance?.openGlobalSearch(`#${tag}`, true);
      });
    }
  }
};

// src/bridge/DataviewBridge.ts
var DataviewBridge = class {
  constructor() {
    this.api = null;
  }
  static getInstance() {
    if (!DataviewBridge.instance) {
      DataviewBridge.instance = new DataviewBridge();
    }
    return DataviewBridge.instance;
  }
  isAvailable() {
    const app = window.app;
    if (!app)
      return false;
    try {
      const dv = window.DataviewAPI;
      return !!dv;
    } catch {
      return false;
    }
  }
  getAPI() {
    if (this.api)
      return this.api;
    try {
      this.api = window.DataviewAPI;
      return this.api;
    } catch {
      return null;
    }
  }
  async executeQuery(query) {
    const dv = this.getAPI();
    if (!dv)
      throw new Error("Dataview not available");
    const result = dv.query(query);
    if (result && result.successful && result.value) {
      return result.value.values ?? [];
    }
    return [];
  }
  async executeTableQuery(query) {
    const dv = this.getAPI();
    if (!dv)
      throw new Error("Dataview not available");
    const result = dv.query(query);
    if (result && result.successful && result.value) {
      return {
        headers: result.value.headers ?? [],
        values: result.value.values ?? []
      };
    }
    return null;
  }
};

// src/widgets/built-in/DataviewTable.ts
var DataviewTableWidget = class extends BaseWidget {
  getType() {
    return "dv-table";
  }
  async renderContent(container, config) {
    container.addClass("xyw-dv-table");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-dv-table") });
    const dv = DataviewBridge.getInstance();
    if (!dv.isAvailable()) {
      container.createEl("div", { cls: "xyw-error", text: t("msg-require-dataview") });
      return;
    }
    const query = config.settings.query;
    if (!query) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    try {
      const result = await dv.executeTableQuery(query);
      if (!result || !result.values.length) {
        container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
        return;
      }
      const table = container.createEl("table", { cls: "xyw-table" });
      const thead = table.createEl("thead");
      const headRow = thead.createEl("tr");
      for (const h of result.headers) {
        headRow.createEl("th", { text: String(h) });
      }
      const tbody = table.createEl("tbody");
      for (const row of result.values) {
        const tr = tbody.createEl("tr");
        for (const cell of row) {
          tr.createEl("td", { text: cell ? String(cell) : "" });
        }
      }
    } catch (e) {
      container.createEl("div", { cls: "xyw-error", text: t2("msg-dataview-query-error", { msg: e.message }) });
    }
  }
};

// src/widgets/built-in/DataviewList.ts
var DataviewListWidget = class extends BaseWidget {
  getType() {
    return "dv-list";
  }
  async renderContent(container, config) {
    container.addClass("xyw-dv-list");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-dv-list") });
    const dv = DataviewBridge.getInstance();
    if (!dv.isAvailable()) {
      container.createEl("div", { cls: "xyw-error", text: t("msg-require-dataview") });
      return;
    }
    const query = config.settings.query;
    if (!query) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    try {
      const values = await dv.executeQuery(query);
      if (!values || !values.length) {
        container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
        return;
      }
      const list = container.createEl("ul", { cls: "xyw-list" });
      for (const row of values) {
        const item = list.createEl("li", { cls: "xyw-list-item" });
        item.textContent = row[0] ? String(row[0]) : "-";
      }
    } catch (e) {
      container.createEl("div", { cls: "xyw-error", text: t2("msg-dataview-query-error", { msg: e.message }) });
    }
  }
};

// src/widgets/built-in/ContainerRow.ts
var ContainerRowWidget = class extends BaseWidget {
  getType() {
    return "container-row";
  }
  async renderContent(container, config) {
    const children = config.children ?? [];
    if (!children.length) {
      container.createEl("div", { cls: "xyw-empty", text: "No children" });
      return;
    }
    container.addClass("xyw-container-row");
    for (const child of children) {
      const cell = container.createEl("div", { cls: "xyw-container-cell" });
      const widget = createWidget(child.type);
      if (widget) {
        await widget.render(cell, {
          type: child.type,
          title: child.name,
          settings: child.settings,
          children: child.children
        });
      }
    }
  }
};

// src/widgets/built-in/ContainerCol.ts
var ContainerColWidget = class extends BaseWidget {
  getType() {
    return "container-col";
  }
  async renderContent(container, config) {
    const children = config.children ?? [];
    if (!children.length) {
      container.createEl("div", { cls: "xyw-empty", text: "No children" });
      return;
    }
    container.addClass("xyw-container-col");
    for (const child of children) {
      const cell = container.createEl("div", { cls: "xyw-container-cell" });
      const widget = createWidget(child.type);
      if (widget) {
        await widget.render(cell, {
          type: child.type,
          title: child.name,
          settings: child.settings,
          children: child.children
        });
      }
    }
  }
};

// src/widgets/built-in/ContainerTab.ts
var ContainerTabWidget = class extends BaseWidget {
  constructor() {
    super(...arguments);
    this.activeIndex = 0;
    this.tabContentEl = null;
  }
  getType() {
    return "container-tab-h";
  }
  async renderContent(container, config) {
    const children = config.children ?? [];
    if (!children.length) {
      container.createEl("div", { cls: "xyw-empty", text: "No children" });
      return;
    }
    const isVertical = config.type === "container-tab-v";
    container.addClass(isVertical ? "xyw-container-tab-v" : "xyw-container-tab-h");
    if (isVertical) {
      const flexRow = container.createEl("div", { cls: "xyw-tab-v-wrapper" });
      const tabBar = flexRow.createEl("div", { cls: "xyw-tab-bar-v" });
      const tabContent = flexRow.createEl("div", { cls: "xyw-tab-content-v" });
      this.tabContentEl = tabContent;
      this.buildTabs(tabBar, tabContent, children, config);
    } else {
      const tabBar = container.createEl("div", { cls: "xyw-tab-bar-h" });
      const tabContent = container.createEl("div", { cls: "xyw-tab-content-h" });
      this.tabContentEl = tabContent;
      this.buildTabs(tabBar, tabContent, children, config);
    }
  }
  buildTabs(tabBar, tabContent, children, config) {
    this.activeIndex = Math.min(this.activeIndex, children.length - 1);
    for (let i = 0; i < children.length; i++) {
      const child = children[i];
      const tabBtn = tabBar.createEl("button", {
        cls: `xyw-tab-btn${i === this.activeIndex ? " xyw-tab-active" : ""}`,
        text: child.name
      });
      tabBtn.addEventListener("click", async () => {
        this.activeIndex = i;
        tabBar.querySelectorAll(".xyw-tab-btn").forEach((el, idx) => {
          el.toggleClass("xyw-tab-active", idx === i);
        });
        tabContent.empty();
        await this.renderChildContent(tabContent, child);
      });
      if (i === this.activeIndex) {
        this.renderChildContent(tabContent, child);
      }
    }
  }
  async renderChildContent(container, child) {
    const widget = createWidget(child.type);
    if (widget) {
      await widget.render(container, {
        type: child.type,
        title: child.name,
        settings: child.settings,
        children: child.children
      });
    }
  }
  destroy() {
    this.tabContentEl = null;
    this.activeIndex = 0;
    super.destroy();
  }
};

// src/renderer/CodeBlockRenderer.ts
var CodeBlockRenderer = class {
  constructor(store) {
    this.store = store;
  }
  async render(source, container) {
    container.empty();
    container.addClass("xyw-block");
    let data;
    try {
      data = this.parseSource(source);
    } catch {
      container.createEl("div", { cls: "xyw-error", text: "Invalid widget config" });
      return;
    }
    const def = this.store.getWidget(data.id);
    if (!def) {
      container.createEl("div", { cls: "xyw-error", text: `Widget "${data.id}" not found. Create it in settings first.` });
      return;
    }
    const widget = createWidget(def.type);
    if (!widget) {
      container.createEl("div", { cls: "xyw-error", text: `Unknown widget type: ${def.type}` });
      return;
    }
    try {
      await widget.render(container, {
        type: def.type,
        title: def.name,
        settings: def.settings,
        children: def.children
      });
    } catch (e) {
      container.empty();
      container.createEl("div", { cls: "xyw-error", text: `Render error: ${e.message}` });
    }
  }
  parseSource(source) {
    const lines = source.trim().split("\n");
    const data = {};
    for (const line of lines) {
      const trimmed = line.trim();
      const colonIdx = trimmed.indexOf(":");
      if (colonIdx < 0)
        continue;
      const key = trimmed.slice(0, colonIdx).trim();
      const value = trimmed.slice(colonIdx + 1).trim();
      if (key && value) {
        data[key] = value;
      }
    }
    if (!data.id) {
      throw new Error("Missing id");
    }
    return { id: data.id };
  }
};

// src/ui/WidgetPickerModal.ts
var import_obsidian = require("obsidian");
var WidgetPickerModal = class extends import_obsidian.Modal {
  constructor(app, store, onSelect) {
    super(app);
    this.store = store;
    this.onSelect = onSelect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("xyw-picker-modal");
    contentEl.createEl("h2", { text: t("title-pick-widget") });
    const widgets = this.store.getWidgets();
    if (!widgets.length) {
      contentEl.createEl("p", { text: t("label-no-widgets") });
      return;
    }
    const list = contentEl.createEl("div", { cls: "xyw-picker-list" });
    for (const w of widgets) {
      const item = list.createEl("div", { cls: "xyw-picker-item" });
      item.createEl("span", { cls: "xyw-picker-name", text: w.name });
      item.createEl("span", { cls: "xyw-picker-type", text: t(`type-${w.type}`) });
      item.createEl("span", { cls: "xyw-picker-id", text: w.id });
      item.addEventListener("click", () => {
        this.onSelect(w.id);
        this.close();
      });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var CONTAINER_TYPES = /* @__PURE__ */ new Set(["container-row", "container-col", "container-tab-h", "container-tab-v"]);
function isContainerType(type) {
  return CONTAINER_TYPES.has(type);
}
var ChildEditorModal = class extends import_obsidian2.Modal {
  constructor(app, existing) {
    super(app);
    this.existing = existing;
    this.result = null;
    this.resolve = null;
  }
  async openAndGet() {
    return new Promise((resolve) => {
      this.resolve = resolve;
      this.open();
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("xyw-editor-modal");
    const isNew = !this.existing;
    contentEl.createEl("h2", { text: isNew ? t("btn-add-child") : t("btn-edit") });
    let name = this.existing?.name ?? "";
    let type = this.existing?.type ?? "stats-card";
    let settings = this.existing?.settings ? { ...this.existing.settings } : {};
    let children = this.existing?.children ? JSON.parse(JSON.stringify(this.existing.children)) : [];
    new import_obsidian2.Setting(contentEl).setName(t("label-name")).addText((tc) => tc.setValue(name).onChange((v) => {
      name = v;
    }));
    new import_obsidian2.Setting(contentEl).setName(t("label-type")).addDropdown((dd) => {
      for (const m of getAllWidgetMetas()) {
        dd.addOption(m.type, t(`type-${m.type}`));
      }
      dd.setValue(type);
      dd.onChange((v) => {
        type = v;
        settings = {};
        const meta2 = getWidgetMeta(type);
        if (meta2) {
          for (const field of meta2.settingSchema) {
            settings[field.key] = field.defaultValue;
          }
        }
        if (!isContainerType(type))
          children = [];
        this.close();
        new ChildEditorModal(this.app, { name, type, settings, children: children.length ? children : void 0 }).open();
      });
    });
    const meta = getWidgetMeta(type);
    if (meta && meta.settingSchema.length > 0) {
      contentEl.createEl("h3", { text: t("label-config") });
      for (const field of meta.settingSchema) {
        const setting = new import_obsidian2.Setting(contentEl).setName(t(field.labelKey));
        const currentVal = settings[field.key] ?? field.defaultValue;
        switch (field.type) {
          case "text":
            setting.addText((tc) => tc.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
              settings[field.key] = v;
            }));
            break;
          case "number":
            setting.addText((t3) => {
              t3.setPlaceholder(field.placeholder ?? "0");
              t3.setValue(String(currentVal));
              t3.inputEl.type = "number";
              t3.onChange((v) => {
                settings[field.key] = Number(v) || 0;
              });
            });
            break;
          case "textarea":
            setting.addTextArea((ta) => ta.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
              settings[field.key] = v;
            }));
            break;
          case "select":
            if (field.options) {
              setting.addDropdown((dd) => {
                for (const opt of field.options)
                  dd.addOption(opt.value, opt.label);
                dd.setValue(String(currentVal));
                dd.onChange((v) => {
                  settings[field.key] = v;
                });
              });
            }
            break;
        }
      }
    }
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText(t("btn-save")).setCta().onClick(() => {
      if (!name.trim()) {
        new import_obsidian2.Notice("Name is required");
        return;
      }
      this.result = { name: name.trim(), type, settings };
      if (isContainerType(type))
        this.result.children = children;
      this.close();
    })).addButton((btn) => btn.setButtonText(t("btn-cancel")).onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
    if (this.resolve)
      this.resolve(this.result);
  }
};
var WidgetEditorModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, store, editId, onSaved) {
    super(app);
    this.plugin = plugin;
    this.store = store;
    this.editId = editId;
    this.onSaved = onSaved;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("xyw-editor-modal");
    const existing = this.editId ? this.store.getWidget(this.editId) : null;
    const isNew = !existing;
    contentEl.createEl("h2", { text: isNew ? t("title-new-widget") : t("title-edit-widget") });
    let name = existing?.name ?? "";
    let type = existing?.type ?? "stats-card";
    let settings = existing?.settings ? { ...existing.settings } : {};
    let children = existing?.children ? JSON.parse(JSON.stringify(existing.children)) : [];
    new import_obsidian2.Setting(contentEl).setName(t("label-name")).addText((tc) => tc.setValue(name).onChange((v) => {
      name = v;
    }));
    if (isNew) {
      new import_obsidian2.Setting(contentEl).setName(t("label-type")).addDropdown((dd) => {
        for (const m of getAllWidgetMetas()) {
          dd.addOption(m.type, t(`type-${m.type}`));
        }
        dd.setValue(type);
        dd.onChange((v) => {
          type = v;
          settings = {};
          const meta2 = getWidgetMeta(type);
          if (meta2)
            for (const field of meta2.settingSchema)
              settings[field.key] = field.defaultValue;
          if (!isContainerType(type))
            children = [];
          this.close();
          new WidgetEditorModal(this.app, this.plugin, this.store, this.editId, this.onSaved).open();
        });
      });
    } else {
      new import_obsidian2.Setting(contentEl).setName(t("label-type")).setDesc(t(`type-${existing.type}`));
    }
    if (isContainerType(type)) {
      contentEl.createEl("h3", { text: t("label-children") });
      if (!children.length) {
        contentEl.createEl("p", { cls: "xyw-empty-state", text: t("msg-no-children") });
      }
      const listEl = contentEl.createEl("div", { cls: "xyw-child-list" });
      const refreshList = () => {
        listEl.empty();
        for (let i = 0; i < children.length; i++) {
          const child = children[i];
          const card = listEl.createEl("div", { cls: "xyw-child-card-simple" });
          const label = card.createEl("span", {
            cls: "xyw-child-label-simple",
            text: `${i + 1}. ${child.name} (${t(`type-${child.type}`)})`
          });
          const acts = card.createEl("div", { cls: "xyw-child-actions-simple" });
          new import_obsidian2.ButtonComponent(acts).setIcon("arrow-up").setTooltip("Move up").onClick(() => {
            if (i > 0) {
              [children[i - 1], children[i]] = [children[i], children[i - 1]];
              refreshList();
            }
          });
          new import_obsidian2.ButtonComponent(acts).setIcon("arrow-down").setTooltip("Move down").onClick(() => {
            if (i < children.length - 1) {
              [children[i], children[i + 1]] = [children[i + 1], children[i]];
              refreshList();
            }
          });
          new import_obsidian2.ButtonComponent(acts).setIcon("pencil").setTooltip(t("btn-edit")).onClick(async () => {
            const modal = new ChildEditorModal(this.app, child);
            const result = await modal.openAndGet();
            if (result) {
              children[i] = result;
              refreshList();
            }
          });
          new import_obsidian2.ButtonComponent(acts).setIcon("trash-2").setTooltip(t("btn-delete")).onClick(() => {
            children.splice(i, 1);
            refreshList();
          });
        }
      };
      refreshList();
      new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText(t("btn-add-child")).setCta().onClick(async () => {
        const modal = new ChildEditorModal(this.app, null);
        const result = await modal.openAndGet();
        if (result) {
          children.push(result);
          refreshList();
        }
      }));
    }
    const meta = getWidgetMeta(type);
    if (meta && meta.settingSchema.length > 0) {
      contentEl.createEl("h3", { text: t("label-config") });
      for (const field of meta.settingSchema) {
        const setting = new import_obsidian2.Setting(contentEl).setName(t(field.labelKey));
        const currentVal = settings[field.key] ?? field.defaultValue;
        switch (field.type) {
          case "text":
            setting.addText((tc) => tc.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
              settings[field.key] = v;
            }));
            break;
          case "number":
            setting.addText((t3) => {
              t3.setPlaceholder(field.placeholder ?? "0");
              t3.setValue(String(currentVal));
              t3.inputEl.type = "number";
              t3.onChange((v) => {
                settings[field.key] = Number(v) || 0;
              });
            });
            break;
          case "textarea":
            setting.addTextArea((ta) => ta.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
              settings[field.key] = v;
            }));
            break;
          case "select":
            if (field.options) {
              setting.addDropdown((dd) => {
                for (const opt of field.options)
                  dd.addOption(opt.value, opt.label);
                dd.setValue(String(currentVal));
                dd.onChange((v) => {
                  settings[field.key] = v;
                });
              });
            }
            break;
        }
      }
    }
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText(t("btn-save")).setCta().onClick(async () => {
      if (!name.trim()) {
        new import_obsidian2.Notice("Name is required");
        return;
      }
      const data = { name: name.trim(), type, settings };
      if (isContainerType(type))
        data.children = children;
      if (isNew) {
        const saved = await this.store.addWidget(data);
        new import_obsidian2.Notice(t("btn-save"));
        this.onSaved(saved);
      } else {
        await this.store.updateWidget(this.editId, data);
        new import_obsidian2.Notice(t("btn-save"));
        this.onSaved();
      }
      this.close();
    })).addButton((btn) => btn.setButtonText(t("btn-cancel")).onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var WidgetSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin, store) {
    super(app, plugin);
    this.plugin = plugin;
    this.store = store;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: t("settings-widget-mgr") });
    new import_obsidian2.Setting(containerEl).setDesc(t("codeblock-hint"));
    new import_obsidian2.Setting(containerEl).addButton((btn) => btn.setButtonText(t("btn-new-widget")).setCta().onClick(() => {
      new WidgetEditorModal(this.app, this.plugin, this.store, null, () => this.display()).open();
    })).addButton((btn) => btn.setButtonText(t("btn-export")).onClick(() => {
      const data = this.store.exportWidgets();
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = "xiaoyuan-widgets.json";
      a.click();
      URL.revokeObjectURL(a.href);
    })).addButton((btn) => btn.setButtonText(t("btn-import")).onClick(() => {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = ".json";
      input.onchange = async () => {
        const file = input.files?.[0];
        if (!file)
          return;
        try {
          const text = await file.text();
          const data = JSON.parse(text);
          const arr = Array.isArray(data) ? data : data.widgets ?? [];
          if (!arr.length) {
            new import_obsidian2.Notice("No valid widgets found.");
            return;
          }
          const count = await this.store.importWidgets(arr);
          new import_obsidian2.Notice(t2("msg-import-success", { n: String(count) }));
          this.display();
        } catch (e) {
          new import_obsidian2.Notice("Import failed: " + e.message);
        }
      };
      input.click();
    }));
    const widgets = this.store.getWidgets();
    if (!widgets.length) {
      containerEl.createEl("p", { cls: "xyw-empty-state", text: t("label-no-widgets") });
      return;
    }
    const list = containerEl.createEl("div", { cls: "xyw-widget-list" });
    for (const w of widgets) {
      const item = list.createEl("div", { cls: "xyw-widget-card" });
      const info = item.createEl("div", { cls: "xyw-widget-info" });
      const parts = [t(`type-${w.type}`), w.id];
      if (w.children?.length)
        parts.push(`[${w.children.length}]`);
      info.createEl("div", { cls: "xyw-widget-name", text: w.name });
      info.createEl("div", { cls: "xyw-widget-meta", text: parts.join(" \xB7 ") });
      const actions = item.createEl("div", { cls: "xyw-widget-actions" });
      new import_obsidian2.ButtonComponent(actions).setIcon("clipboard-copy").setTooltip("Copy code block").onClick(() => {
        navigator.clipboard.writeText(`\`\`\`xiaoyuanwidget
id: ${w.id}
\`\`\``).then(() => new import_obsidian2.Notice(t("msg-copied")));
      });
      new import_obsidian2.ButtonComponent(actions).setIcon("pencil").setTooltip(t("btn-edit")).onClick(() => {
        new WidgetEditorModal(this.app, this.plugin, this.store, w.id, () => this.display()).open();
      });
      new import_obsidian2.ButtonComponent(actions).setIcon("trash-2").setTooltip(t("btn-delete")).onClick(async () => {
        if (confirm(t2("msg-confirm-delete", { name: w.name }))) {
          await this.store.deleteWidget(w.id);
          this.display();
        }
      });
    }
  }
};

// src/main.ts
var WidgetPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    const lang = getLang();
    setLang(lang);
    this.store = new WidgetStore(
      () => this.loadData(),
      (data) => this.saveData(data)
    );
    this.renderer = new CodeBlockRenderer(this.store);
    this.registerWidgetTypes();
    this.registerCodeBlockProcessor();
    this.registerContextMenu();
    this.registerCommands();
    this.registerSettingTab();
  }
  registerWidgetTypes() {
    const metas = [
      {
        type: "stats-card",
        defaultTitle: t("type-stats-card"),
        description: "Display vault statistics as a card",
        settingSchema: [
          {
            key: "dimension",
            labelKey: "config-dimension",
            type: "select",
            defaultValue: "total",
            options: [
              { label: t("stats-total-notes"), value: "total" },
              { label: t("stats-today"), value: "today" },
              { label: t("stats-week"), value: "week" }
            ]
          }
        ]
      },
      {
        type: "recent-files",
        defaultTitle: t("type-recent-files"),
        description: "List recently modified files",
        settingSchema: [
          {
            key: "limit",
            labelKey: "config-limit",
            type: "number",
            defaultValue: 10,
            placeholder: "10"
          },
          {
            key: "excludeFolders",
            labelKey: "config-exclude-folders",
            type: "textarea",
            defaultValue: "",
            placeholder: "folder1/, folder2/"
          }
        ]
      },
      {
        type: "tag-cloud",
        defaultTitle: t("type-tag-cloud"),
        description: "Display tags as a cloud",
        settingSchema: [
          {
            key: "minCount",
            labelKey: "config-min-count",
            type: "number",
            defaultValue: 1,
            placeholder: "1"
          }
        ]
      },
      {
        type: "dv-table",
        defaultTitle: t("type-dv-table"),
        description: "Execute a Dataview query and display as table",
        settingSchema: [
          {
            key: "query",
            labelKey: "config-query",
            type: "textarea",
            defaultValue: "",
            placeholder: 'TABLE file.ctime FROM ""'
          }
        ]
      },
      {
        type: "dv-list",
        defaultTitle: t("type-dv-list"),
        description: "Execute a Dataview query and display as list",
        settingSchema: [
          {
            key: "query",
            labelKey: "config-query",
            type: "textarea",
            defaultValue: "",
            placeholder: 'FROM "projects"'
          }
        ]
      },
      {
        type: "container-row",
        defaultTitle: t("type-container-row"),
        description: "Arrange child widgets in a horizontal row",
        settingSchema: []
      },
      {
        type: "container-col",
        defaultTitle: t("type-container-col"),
        description: "Arrange child widgets in a vertical column",
        settingSchema: []
      },
      {
        type: "container-tab-h",
        defaultTitle: t("type-container-tab-h"),
        description: "Arrange child widgets as horizontal tabs",
        settingSchema: []
      },
      {
        type: "container-tab-v",
        defaultTitle: t("type-container-tab-v"),
        description: "Arrange child widgets as vertical tabs",
        settingSchema: []
      }
    ];
    const widgets = [
      { ctor: StatsCardWidget, meta: metas[0] },
      { ctor: RecentFilesWidget, meta: metas[1] },
      { ctor: TagCloudWidget, meta: metas[2] },
      { ctor: DataviewTableWidget, meta: metas[3] },
      { ctor: DataviewListWidget, meta: metas[4] },
      { ctor: ContainerRowWidget, meta: metas[5] },
      { ctor: ContainerColWidget, meta: metas[6] },
      { ctor: ContainerTabWidget, meta: metas[7] },
      { ctor: ContainerTabWidget, meta: metas[8] }
    ];
    for (const { ctor, meta } of widgets) {
      registerWidgetType(ctor, meta);
    }
  }
  registerCodeBlockProcessor() {
    this.registerMarkdownCodeBlockProcessor("xiaoyuanwidget", async (source, el, ctx) => {
      await this.renderer.render(source, el);
    });
  }
  registerContextMenu() {
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        let rootSub;
        menu.addItem((item) => {
          item.setTitle(t("context-insert-widget"));
          rootSub = item.setSubmenu();
        });
        if (!rootSub)
          return;
        rootSub.addItem((item) => {
          item.setTitle(t("context-new-widget"));
          item.setIcon("plus");
          item.onClick(() => {
            new WidgetEditorModal(this.app, this, this.store, null, (widget) => {
              if (widget)
                this.insertCodeBlock(editor, widget.id);
            }).open();
          });
        });
        const widgets = this.store.getWidgets();
        if (widgets.length === 0) {
          rootSub.addItem((item) => {
            item.setTitle(t("label-no-widgets"));
            item.setDisabled(true);
          });
          return;
        }
        let insertSub;
        rootSub.addItem((item) => {
          item.setTitle(t("context-insert-wgt"));
          insertSub = item.setSubmenu();
        });
        if (!insertSub)
          return;
        const grouped = /* @__PURE__ */ new Map();
        for (const w of widgets) {
          const list = grouped.get(w.type) || [];
          list.push(w);
          grouped.set(w.type, list);
        }
        const typeOrder = getAllWidgetTypes();
        for (const type of typeOrder) {
          const list = grouped.get(type);
          if (!list || list.length === 0)
            continue;
          let typeSub;
          insertSub.addItem((item) => {
            item.setTitle(t(`type-${type}`));
            typeSub = item.setSubmenu();
          });
          if (!typeSub)
            continue;
          for (const w of list) {
            typeSub.addItem((item) => {
              item.setTitle(w.name);
              item.onClick(() => {
                this.insertCodeBlock(editor, w.id);
              });
            });
          }
        }
      })
    );
  }
  insertCodeBlock(editor, id) {
    const code = `\`\`\`xiaoyuanwidget
id: ${id}
\`\`\``;
    const cursor = editor.getCursor();
    editor.replaceRange(code, cursor);
    editor.setCursor({
      line: cursor.line + 3,
      ch: 0
    });
  }
  registerCommands() {
    this.addCommand({
      id: "insert-widget",
      name: "Insert widget at cursor",
      editorCallback: (editor, view) => {
        new WidgetPickerModal(this.app, this.store, (id) => {
          this.insertCodeBlock(editor, id);
        }).open();
      }
    });
  }
  registerSettingTab() {
    this.addSettingTab(new WidgetSettingTab(this.app, this, this.store));
  }
};
