/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WidgetPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/utils.ts
function generateId() {
  const d = new Date();
  const pad = (n, len = 2) => String(n).padStart(len, "0");
  const rand = Math.random().toString(36).substring(2, 6);
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}_${rand}`;
}

// src/store/WidgetStore.ts
var WidgetStore = class {
  constructor(loadData, saveData) {
    this.data = { widgets: [] };
    this.saveFn = async () => {
      await saveData(this.data);
    };
    this.init(loadData);
  }
  async init(loadData) {
    const loaded = await loadData();
    if (loaded && loaded.widgets) {
      this.data = loaded;
    }
  }
  getWidgets() {
    return this.data.widgets;
  }
  getWidget(id) {
    return this.data.widgets.find((w) => w.id === id);
  }
  async addWidget(def) {
    const widget = {
      ...def,
      id: generateId(),
      createdAt: Date.now(),
      updatedAt: Date.now()
    };
    this.data.widgets.push(widget);
    await this.saveFn();
    return widget;
  }
  async updateWidget(id, updates) {
    const idx = this.data.widgets.findIndex((w) => w.id === id);
    if (idx === -1)
      return false;
    this.data.widgets[idx] = {
      ...this.data.widgets[idx],
      ...updates,
      updatedAt: Date.now()
    };
    await this.saveFn();
    return true;
  }
  async deleteWidget(id) {
    const idx = this.data.widgets.findIndex((w) => w.id === id);
    if (idx === -1)
      return false;
    this.data.widgets.splice(idx, 1);
    await this.saveFn();
    return true;
  }
  async importWidgets(defs) {
    const now = Date.now();
    for (const def of defs) {
      if (!this.getWidget(def.id)) {
        this.data.widgets.push({
          ...def,
          createdAt: now,
          updatedAt: now
        });
      }
    }
    await this.saveFn();
    return defs.length;
  }
  exportWidgets() {
    return JSON.parse(JSON.stringify(this.data.widgets));
  }
};

// src/widgets/registry.ts
var widgetMap = /* @__PURE__ */ new Map();
var metaMap = /* @__PURE__ */ new Map();
function registerWidgetType(ctor, meta) {
  widgetMap.set(meta.type, ctor);
  metaMap.set(meta.type, meta);
}
function createWidget(type) {
  const Ctor = widgetMap.get(type);
  if (!Ctor)
    return null;
  return new Ctor();
}
function getWidgetMeta(type) {
  return metaMap.get(type);
}
function getAllWidgetMetas() {
  return Array.from(metaMap.values());
}
function getAllWidgetTypes() {
  return Array.from(metaMap.keys());
}

// src/utils/StyleUtils.ts
function applyWidgetStyle(container, config) {
  const style = config.style;
  if (!style)
    return;
  if (style.borderColor) {
    container.style.borderColor = style.borderColor;
  }
  if (style.width || style.height) {
    container.style.flex = "none";
  }
  if (style.width) {
    container.style.width = style.width;
  }
  if (style.height) {
    container.style.height = style.height;
  }
  const titleEl = container.querySelector(".xyw-card-title");
  if (titleEl && style.title) {
    if (style.title.align)
      titleEl.style.textAlign = style.title.align;
    if (style.title.color)
      titleEl.style.color = style.title.color;
    if (style.title.bgColor)
      titleEl.style.backgroundColor = style.title.bgColor;
    if (style.title.fontSize)
      titleEl.style.fontSize = style.title.fontSize;
    if (style.title.fontWeight)
      titleEl.style.fontWeight = style.title.fontWeight;
  }
  if (style.content) {
    if (style.content.align)
      container.style.textAlign = style.content.align;
    if (style.content.color)
      container.style.color = style.content.color;
    if (style.content.fontSize)
      container.style.fontSize = style.content.fontSize;
    if (style.content.fontWeight)
      container.style.fontWeight = style.content.fontWeight;
  }
}
function getFieldValue(item, source, field) {
  if (source === "fileprop") {
    switch (field) {
      case "path":
        return item.path ?? "";
      case "name":
        return item.name ?? "";
      case "ctime":
        return String(item.stat?.ctime ?? "");
      case "mtime":
        return String(item.stat?.mtime ?? "");
      case "size":
        return String(item.stat?.size ?? "");
      default:
        return "";
    }
  }
  if (source === "yaml") {
    const metadata = item.metadataCache ?? item.frontmatter ?? {};
    const val = metadata[field];
    if (val == null)
      return "";
    if (Array.isArray(val))
      return val.join(", ");
    return String(val);
  }
  return "";
}
function compareValue(val, operator, target) {
  switch (operator) {
    case "contains":
      return val.toLowerCase().includes(target.toLowerCase());
    case "not_contains":
      return !val.toLowerCase().includes(target.toLowerCase());
    case "equals":
      return val.toLowerCase() === target.toLowerCase();
    case "not_equals":
      return val.toLowerCase() !== target.toLowerCase();
    case "gt":
      return Number(val) > Number(target);
    case "lt":
      return Number(val) < Number(target);
    default:
      return true;
  }
}
function applyFilters(items, filters) {
  if (!filters || filters.length === 0)
    return items;
  return items.filter((item) => {
    let result = true;
    for (let i = 0; i < filters.length; i++) {
      const rule = filters[i];
      const val = getFieldValue(item, rule.source, rule.field);
      const matched = compareValue(val, rule.operator, rule.value);
      if (i === 0) {
        result = matched;
        continue;
      }
      if (rule.logic === "and")
        result = result && matched;
      else
        result = result || matched;
    }
    return result;
  });
}

// src/widgets/base.ts
var BaseWidget = class {
  constructor() {
    this.container = null;
    this.config = null;
    this._active = false;
  }
  async render(container, config) {
    this.container = container;
    this.config = config;
    this._active = true;
    container.empty();
    await this.renderContent(container, config);
    applyWidgetStyle(container, config);
  }
  async refresh() {
    if (this.container && this.config && this._active) {
      await this.render(this.container, this.config);
    }
  }
  destroy() {
    this._active = false;
    this.container = null;
    this.config = null;
  }
};

// src/i18n.ts
var currentLang = "zh";
var translations = {
  "plugin-name": { en: "xiaoyuanWidget", zh: "\u5C0F\u5143\u6302\u4EF6" },
  "plugin-desc": { en: "Modular widgets \u2014 stats, Dataview queries, tag cloud and more", zh: "\u6A21\u5757\u5316\u6302\u4EF6 \u2014 \u7EDF\u8BA1\u3001Dataview \u67E5\u8BE2\u3001\u6807\u7B7E\u4E91\u7B49" },
  "settings-general": { en: "General Settings", zh: "\u901A\u7528\u8BBE\u7F6E" },
  "settings-widget-mgr": { en: "Widget Manager", zh: "\u6302\u4EF6\u7BA1\u7406" },
  "settings-dataview": { en: "Dataview Integration", zh: "Dataview \u96C6\u6210" },
  "btn-new-widget": { en: "New Widget", zh: "\u65B0\u5EFA\u6302\u4EF6" },
  "btn-edit": { en: "Edit", zh: "\u7F16\u8F91" },
  "btn-delete": { en: "Delete", zh: "\u5220\u9664" },
  "btn-save": { en: "Save", zh: "\u4FDD\u5B58" },
  "btn-cancel": { en: "Cancel", zh: "\u53D6\u6D88" },
  "btn-insert": { en: "Insert", zh: "\u63D2\u5165" },
  "btn-export": { en: "Export", zh: "\u5BFC\u51FA" },
  "btn-import": { en: "Import", zh: "\u5BFC\u5165" },
  "btn-import-all": { en: "Import All", zh: "\u5168\u90E8\u5BFC\u5165" },
  "label-name": { en: "Name", zh: "\u540D\u79F0" },
  "label-id": { en: "ID", zh: "ID" },
  "label-type": { en: "Type", zh: "\u7C7B\u578B" },
  "label-config": { en: "Configuration", zh: "\u914D\u7F6E" },
  "label-usage-count": { en: "Usage Count", zh: "\u4F7F\u7528\u6B21\u6570" },
  "label-created": { en: "Created", zh: "\u521B\u5EFA\u65F6\u95F4" },
  "label-updated": { en: "Updated", zh: "\u66F4\u65B0\u65F6\u95F4" },
  "label-no-widgets": { en: 'No widgets yet. Click "New Widget" to create one.', zh: '\u6682\u65E0\u6302\u4EF6\uFF0C\u70B9\u51FB"\u65B0\u5EFA\u6302\u4EF6"\u521B\u5EFA\u7B2C\u4E00\u4E2A\u3002' },
  "label-widget-id": { en: "Widget ID", zh: "\u6302\u4EF6 ID" },
  "label-select-widget": { en: "Select a widget", zh: "\u9009\u62E9\u4E00\u4E2A\u6302\u4EF6" },
  "label-find-references": { en: "Find References", zh: "\u67E5\u627E\u5F15\u7528" },
  "title-edit-widget": { en: "Edit Widget", zh: "\u7F16\u8F91\u6302\u4EF6" },
  "title-new-widget": { en: "New Widget", zh: "\u65B0\u5EFA\u6302\u4EF6" },
  "title-pick-widget": { en: "Insert xiaoyuanWidget", zh: "\u63D2\u5165\u5C0F\u5143\u6302\u4EF6" },
  "title-widget-preview": { en: "Preview", zh: "\u9884\u89C8" },
  "msg-confirm-delete": { en: 'Are you sure you want to delete "{name}"?', zh: '\u786E\u5B9A\u5220\u9664\u6302\u4EF6"{name}"\u5417\uFF1F' },
  "msg-widget-exists": { en: "A widget with this ID already exists.", zh: "\u6B64 ID \u5DF2\u5B58\u5728\u3002" },
  "msg-require-dataview": { en: "Dataview plugin is required. Install and enable it first.", zh: "\u9700\u8981 Dataview \u63D2\u4EF6\uFF0C\u8BF7\u5148\u5B89\u88C5\u5E76\u542F\u7528\u3002" },
  "msg-dataview-query-error": { en: "Query error: {msg}", zh: "\u67E5\u8BE2\u9519\u8BEF\uFF1A{msg}" },
  "msg-no-data": { en: "No data.", zh: "\u6682\u65E0\u6570\u636E\u3002" },
  "msg-import-success": { en: "Imported {n} widget(s).", zh: "\u5DF2\u5BFC\u5165 {n} \u4E2A\u6302\u4EF6\u3002" },
  "msg-copied": { en: "Copied to clipboard!", zh: "\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F\uFF01" },
  "type-stats-card": { en: "Stats Card", zh: "\u7EDF\u8BA1\u5361\u7247" },
  "type-recent-files": { en: "Recent Files", zh: "\u6700\u8FD1\u6587\u4EF6" },
  "type-tag-cloud": { en: "Tag Cloud", zh: "\u6807\u7B7E\u4E91" },
  "type-dv-table": { en: "Dataview Table", zh: "Dataview \u8868\u683C" },
  "type-dv-list": { en: "Dataview List", zh: "Dataview \u5217\u8868" },
  "type-container-row": { en: "Row", zh: "\u884C\u6392\u5217" },
  "type-container-col": { en: "Column", zh: "\u5217\u6392\u5217" },
  "type-container-tab-h": { en: "Horizontal Tabs", zh: "\u6807\u7B7E\u6C34\u5E73\u6392\u5217" },
  "type-container-tab-v": { en: "Vertical Tabs", zh: "\u6807\u7B7E\u5782\u76F4\u6392\u5217" },
  "type-backlinks": { en: "Backlinks", zh: "\u53CD\u5411\u94FE\u63A5" },
  "type-random-note": { en: "Random Note", zh: "\u968F\u673A\u7B14\u8BB0" },
  "stats-total-notes": { en: "Total Notes", zh: "\u7B14\u8BB0\u603B\u6570" },
  "stats-today": { en: "Created Today", zh: "\u4ECA\u65E5\u65B0\u5EFA" },
  "stats-week": { en: "This Week", zh: "\u672C\u5468\u65B0\u5EFA" },
  "config-dimension": { en: "Dimension", zh: "\u7EDF\u8BA1\u7EF4\u5EA6" },
  "config-limit": { en: "Max Items", zh: "\u6700\u5927\u6761\u6570" },
  "config-exclude-folders": { en: "Exclude Folders", zh: "\u6392\u9664\u76EE\u5F55" },
  "config-min-count": { en: "Min Count", zh: "\u6700\u5C11\u51FA\u73B0\u6B21\u6570" },
  "config-query": { en: "DQL Query", zh: "DQL \u67E5\u8BE2\u8BED\u53E5" },
  "label-children": { en: "Children", zh: "\u5B50\u6302\u4EF6" },
  "label-layout-type": { en: "Layout", zh: "\u5B50\u6302\u4EF6\u6392\u5217\u65B9\u5F0F" },
  "label-widget-list": { en: "Widgets", zh: "\u6302\u4EF6\u5217\u8868" },
  "label-child-list": { en: "Widgets", zh: "\u5B50\u6302\u4EF6\u5217\u8868" },
  "btn-rename": { en: "Rename", zh: "\u91CD\u547D\u540D" },
  "btn-add-child": { en: "Add Child", zh: "\u6DFB\u52A0\u5B50\u6302\u4EF6" },
  "btn-switch-type-warn": { en: "Switching to a non-container type will clear all children. Continue?", zh: "\u5207\u6362\u4E3A\u975E\u5BB9\u5668\u7C7B\u578B\u5C06\u6E05\u9664\u6240\u6709\u5B50\u6302\u4EF6\uFF0C\u662F\u5426\u7EE7\u7EED\uFF1F" },
  "msg-no-children": { en: 'No children. Click "Add Child" to add one.', zh: '\u6682\u65E0\u5B50\u6302\u4EF6\uFF0C\u70B9\u51FB"\u6DFB\u52A0\u5B50\u6302\u4EF6"\u6DFB\u52A0\u3002' },
  "style-title": { en: "Title Style", zh: "\u6807\u9898\u6837\u5F0F" },
  "style-title-align": { en: "Title Align", zh: "\u6807\u9898\u5BF9\u9F50" },
  "style-title-color": { en: "Title Color", zh: "\u6807\u9898\u6587\u5B57\u989C\u8272" },
  "style-title-bg": { en: "Title Background", zh: "\u6807\u9898\u80CC\u666F\u8272" },
  "style-title-size": { en: "Title Font Size", zh: "\u6807\u9898\u6587\u5B57\u5927\u5C0F" },
  "style-title-weight": { en: "Title Font Weight", zh: "\u6807\u9898\u6587\u5B57\u7C97\u7EC6" },
  "style-content": { en: "Content Style", zh: "\u5185\u5BB9\u6837\u5F0F" },
  "style-content-align": { en: "Content Align", zh: "\u5185\u5BB9\u5BF9\u9F50" },
  "style-content-color": { en: "Content Color", zh: "\u5185\u5BB9\u6587\u5B57\u989C\u8272" },
  "style-content-size": { en: "Content Font Size", zh: "\u5185\u5BB9\u6587\u5B57\u5927\u5C0F" },
  "style-content-weight": { en: "Content Font Weight", zh: "\u5185\u5BB9\u6587\u5B57\u7C97\u7EC6" },
  "style-border-color": { en: "Border Color", zh: "\u8FB9\u6846\u989C\u8272" },
  "style-width": { en: "Width", zh: "\u5BBD\u5EA6" },
  "style-height": { en: "Height", zh: "\u9AD8\u5EA6" },
  "style-align-left": { en: "Left", zh: "\u5DE6\u5BF9\u9F50" },
  "style-align-center": { en: "Center", zh: "\u5C45\u4E2D" },
  "style-align-right": { en: "Right", zh: "\u53F3\u5BF9\u9F50" },
  "weight-default": { en: "Default", zh: "\u9ED8\u8BA4" },
  "weight-normal": { en: "Normal", zh: "\u5E38\u89C4" },
  "weight-bold": { en: "Bold", zh: "\u7C97\u4F53" },
  "filter-title": { en: "Filter", zh: "\u7B5B\u9009" },
  "filter-add": { en: "Add Filter", zh: "\u6DFB\u52A0\u7B5B\u9009\u6761\u4EF6" },
  "filter-source": { en: "Source", zh: "\u6765\u6E90" },
  "filter-source-yaml": { en: "YAML Property", zh: "YAML \u5C5E\u6027" },
  "filter-source-fileprop": { en: "File Property", zh: "\u6587\u4EF6\u5C5E\u6027" },
  "filter-field": { en: "Field", zh: "\u5B57\u6BB5" },
  "filter-operator": { en: "Operator", zh: "\u64CD\u4F5C\u7B26" },
  "filter-op-contains": { en: "contains", zh: "\u5305\u542B" },
  "filter-op-not_contains": { en: "not contains", zh: "\u4E0D\u5305\u542B" },
  "filter-op-equals": { en: "equals", zh: "\u7B49\u4E8E" },
  "filter-op-not_equals": { en: "not equals", zh: "\u4E0D\u7B49\u4E8E" },
  "filter-op-gt": { en: "greater than", zh: "\u5927\u4E8E" },
  "filter-op-lt": { en: "less than", zh: "\u5C0F\u4E8E" },
  "filter-value": { en: "Value", zh: "\u503C" },
  "filter-logic": { en: "Logic", zh: "\u903B\u8F91" },
  "context-insert-widget": { en: "xiaoyuanWidget", zh: "\u5C0F\u5143\u6302\u4EF6" },
  "context-new-widget": { en: "New Widget", zh: "\u65B0\u5EFA" },
  "context-insert-wgt": { en: "Insert Widget", zh: "\u63D2\u5165" },
  "codeblock-hint": { en: "Right-click to insert a widget, or manually write:\n```xiaoyuanwidget\nid: your-widget-id\n```", zh: "\u53F3\u952E\u53EF\u63D2\u5165\u6302\u4EF6\uFF0C\u6216\u624B\u52A8\u7F16\u5199\uFF1A\n```xiaoyuanwidget\nid: your-widget-id\n```" }
};
function getLang() {
  const locale = window.moment?.locale?.() ?? "en";
  return locale.startsWith("zh") ? "zh" : "en";
}
function setLang(lang) {
  currentLang = lang;
}
function t(key, lang) {
  const l = lang ?? currentLang;
  return translations[key]?.[l] ?? key;
}
function t2(key, vars, lang) {
  const l = lang ?? currentLang;
  const str = translations[key]?.[l] ?? key;
  return str.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}

// src/widgets/built-in/StatsCard.ts
var StatsCardWidget = class extends BaseWidget {
  getType() {
    return "stats-card";
  }
  async renderContent(container, config) {
    const app = window.app;
    if (!app)
      return;
    const vault = app.vault;
    let files = vault.getMarkdownFiles();
    files = applyFilters(files, config.filters);
    const dimension = config.settings.dimension ?? "total";
    let value;
    let label;
    switch (dimension) {
      case "today": {
        const today = new Date();
        const todayStr = today.toISOString().slice(0, 10);
        value = files.filter((f) => {
          const ctime = new Date(f.stat.ctime);
          return ctime.toISOString().slice(0, 10) === todayStr;
        }).length;
        label = t("stats-today");
        break;
      }
      case "week": {
        const weekAgo = Date.now() - 7 * 24 * 60 * 60 * 1e3;
        value = files.filter((f) => f.stat.ctime > weekAgo).length;
        label = t("stats-week");
        break;
      }
      default: {
        value = files.length;
        label = t("stats-total-notes");
        break;
      }
    }
    const title = config.title || label;
    container.addClass("xyw-stats-card");
    container.createEl("div", { cls: "xyw-card-title", text: title });
    const valEl = container.createEl("div", { cls: "xyw-card-value", text: String(value) });
    container.createEl("div", { cls: "xyw-card-label", text: label });
  }
};

// src/widgets/built-in/RecentFiles.ts
var RecentFilesWidget = class extends BaseWidget {
  getType() {
    return "recent-files";
  }
  async renderContent(container, config) {
    const app = window.app;
    if (!app)
      return;
    const vault = app.vault;
    const limit = config.settings.limit ?? 10;
    const excludeFolders = (config.settings.excludeFolders ?? "").split(",").map((s) => s.trim()).filter(Boolean);
    let files = vault.getMarkdownFiles();
    files = applyFilters(files, config.filters);
    files = files.filter((f) => {
      if (!excludeFolders.length)
        return true;
      return !excludeFolders.some((folder) => f.path.startsWith(folder));
    }).sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, limit);
    container.addClass("xyw-recent-files");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-recent-files") });
    if (!files.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    const list = container.createEl("ul", { cls: "xyw-file-list" });
    for (const file of files) {
      const item = list.createEl("li", { cls: "xyw-file-item" });
      item.textContent = file.name;
      item.setAttr("data-path", file.path);
      item.addEventListener("click", () => {
        app.workspace.getLeaf(false).openFile(file);
      });
    }
  }
};

// src/widgets/built-in/TagCloud.ts
var TagCloudWidget = class extends BaseWidget {
  getType() {
    return "tag-cloud";
  }
  async renderContent(container, config) {
    const app = window.app;
    if (!app)
      return;
    const vault = app.vault;
    const minCount = config.settings.minCount ?? 1;
    let files = vault.getMarkdownFiles();
    files = applyFilters(files, config.filters);
    const cache = app.metadataCache;
    const tagCount = /* @__PURE__ */ new Map();
    for (const file of files) {
      const metadata = cache.getFileCache(file);
      if (!metadata)
        continue;
      const seen = /* @__PURE__ */ new Set();
      const processTag = (tag) => {
        const cleanTag = String(tag).replace(/^#/, "");
        if (!cleanTag || seen.has(cleanTag))
          return;
        seen.add(cleanTag);
        tagCount.set(cleanTag, (tagCount.get(cleanTag) ?? 0) + 1);
      };
      if (metadata.frontmatter?.tags) {
        const tags = metadata.frontmatter.tags;
        const tagArr = Array.isArray(tags) ? tags : [tags];
        for (const tag of tagArr)
          processTag(tag);
      }
      if (metadata.tags) {
        for (const t3 of metadata.tags)
          processTag(t3.tag);
      }
    }
    const sorted = Array.from(tagCount.entries()).filter(([_, count]) => count >= minCount).sort((a, b) => b[1] - a[1]);
    container.addClass("xyw-tag-cloud");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-tag-cloud") });
    if (!sorted.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    const maxCount = sorted[0][1];
    const wrapper = container.createEl("div", { cls: "xyw-tags-wrapper" });
    for (const [tag, count] of sorted) {
      const size = 0.8 + count / maxCount * 1.2;
      const el = wrapper.createEl("span", {
        cls: "xyw-tag-item",
        text: `#${tag}`
      });
      el.style.fontSize = `${size}em`;
      el.setAttr("title", `${tag} (${count})`);
      el.addEventListener("click", () => {
        window.app.internalPlugins.getPluginById("global-search")?.instance?.openGlobalSearch(`#${tag}`, true);
      });
    }
  }
};

// src/bridge/DataviewBridge.ts
var DataviewBridge = class {
  constructor() {
    this.api = null;
  }
  static getInstance() {
    if (!DataviewBridge.instance) {
      DataviewBridge.instance = new DataviewBridge();
    }
    return DataviewBridge.instance;
  }
  isAvailable() {
    const app = window.app;
    if (!app)
      return false;
    try {
      const dv = window.DataviewAPI;
      return !!dv;
    } catch {
      return false;
    }
  }
  getAPI() {
    if (this.api)
      return this.api;
    try {
      this.api = window.DataviewAPI;
      return this.api;
    } catch {
      return null;
    }
  }
  async query(query) {
    const dv = this.getAPI();
    if (!dv)
      throw new Error("Dataview not available");
    const result = dv.query(query);
    if (!result || !result.successful || !result.value)
      return null;
    return {
      type: result.value.type ?? "list",
      headers: result.value.headers ?? [],
      values: result.value.values ?? []
    };
  }
};

// src/widgets/built-in/DataviewTable.ts
var DataviewTableWidget = class extends BaseWidget {
  getType() {
    return "dv-table";
  }
  async renderContent(container, config) {
    container.addClass("xyw-dv-table");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || "Dataview Table" });
    const dv = DataviewBridge.getInstance();
    if (!dv.isAvailable()) {
      container.createEl("div", { cls: "xyw-error", text: t("msg-require-dataview") });
      return;
    }
    const query = config.settings.query;
    if (!query) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    try {
      const result = await dv.query(query);
      if (!result || !result.values.length) {
        container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
        return;
      }
      const table = container.createEl("table", { cls: "xyw-table" });
      const thead = table.createEl("thead");
      const headRow = thead.createEl("tr");
      for (const h of result.headers) {
        headRow.createEl("th", { text: String(h) });
      }
      const tbody = table.createEl("tbody");
      for (const row of result.values) {
        const tr = tbody.createEl("tr");
        for (const cell of row) {
          tr.createEl("td", { text: cell ? String(cell) : "" });
        }
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      container.createEl("div", { cls: "xyw-error", text: t2("msg-dataview-query-error", { msg: message }) });
    }
  }
};

// src/widgets/built-in/DataviewList.ts
var DataviewListWidget = class extends BaseWidget {
  getType() {
    return "dv-list";
  }
  async renderContent(container, config) {
    container.addClass("xyw-dv-list");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || "Dataview List" });
    const dv = DataviewBridge.getInstance();
    if (!dv.isAvailable()) {
      container.createEl("div", { cls: "xyw-error", text: t("msg-require-dataview") });
      return;
    }
    const query = config.settings.query;
    if (!query) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    try {
      const result = await dv.query(query);
      if (!result || !result.values.length) {
        container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
        return;
      }
      const list = container.createEl("ul", { cls: "xyw-list" });
      for (const row of result.values) {
        const item = list.createEl("li", { cls: "xyw-list-item" });
        const text = row.map((v) => v != null ? String(v) : "-").join(" \xB7 ");
        item.textContent = text;
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      container.createEl("div", { cls: "xyw-error", text: t2("msg-dataview-query-error", { msg: message }) });
    }
  }
};

// src/widgets/built-in/ContainerRow.ts
var ContainerRowWidget = class extends BaseWidget {
  getType() {
    return "container-row";
  }
  async renderContent(container, config) {
    const children = config.children ?? [];
    if (!children.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-children") });
      return;
    }
    container.addClass("xyw-container-row");
    for (const child of children) {
      const cell = container.createEl("div", { cls: "xyw-container-cell" });
      const widget = createWidget(child.type);
      if (widget) {
        await widget.render(cell, {
          type: child.type,
          title: child.name,
          settings: child.settings,
          children: child.children,
          style: child.style,
          filters: child.filters
        });
      }
    }
  }
};

// src/widgets/built-in/ContainerCol.ts
var ContainerColWidget = class extends BaseWidget {
  getType() {
    return "container-col";
  }
  async renderContent(container, config) {
    const children = config.children ?? [];
    if (!children.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-children") });
      return;
    }
    container.addClass("xyw-container-col");
    for (const child of children) {
      const cell = container.createEl("div", { cls: "xyw-container-cell" });
      const widget = createWidget(child.type);
      if (widget) {
        await widget.render(cell, {
          type: child.type,
          title: child.name,
          settings: child.settings,
          children: child.children,
          style: child.style,
          filters: child.filters
        });
      }
    }
  }
};

// src/widgets/built-in/ContainerTab.ts
var BaseContainerTabWidget = class extends BaseWidget {
  constructor() {
    super(...arguments);
    this.activeIndex = 0;
    this.tabContentEl = null;
  }
  async renderContent(container, config) {
    const children = config.children ?? [];
    if (!children.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-children") });
      return;
    }
    const isVertical = config.type === "container-tab-v";
    container.addClass(isVertical ? "xyw-container-tab-v" : "xyw-container-tab-h");
    if (isVertical) {
      const flexRow = container.createEl("div", { cls: "xyw-tab-v-wrapper" });
      const tabBar = flexRow.createEl("div", { cls: "xyw-tab-bar-v" });
      const tabContent = flexRow.createEl("div", { cls: "xyw-tab-content-v" });
      this.tabContentEl = tabContent;
      this.buildTabs(tabBar, tabContent, children, config);
    } else {
      const tabBar = container.createEl("div", { cls: "xyw-tab-bar-h" });
      const tabContent = container.createEl("div", { cls: "xyw-tab-content-h" });
      this.tabContentEl = tabContent;
      this.buildTabs(tabBar, tabContent, children, config);
    }
  }
  buildTabs(tabBar, tabContent, children, config) {
    this.activeIndex = Math.min(this.activeIndex, children.length - 1);
    for (let i = 0; i < children.length; i++) {
      const child = children[i];
      const tabBtn = tabBar.createEl("button", {
        cls: `xyw-tab-btn${i === this.activeIndex ? " xyw-tab-active" : ""}`,
        text: child.name
      });
      tabBtn.addEventListener("click", async () => {
        this.activeIndex = i;
        tabBar.querySelectorAll(".xyw-tab-btn").forEach((el, idx) => {
          el.toggleClass("xyw-tab-active", idx === i);
        });
        tabContent.empty();
        await this.renderChildContent(tabContent, child);
      });
      if (i === this.activeIndex) {
        this.renderChildContent(tabContent, child);
      }
    }
  }
  async renderChildContent(container, child) {
    const widget = createWidget(child.type);
    if (widget) {
      await widget.render(container, {
        type: child.type,
        title: child.name,
        settings: child.settings,
        children: child.children,
        style: child.style,
        filters: child.filters
      });
    }
  }
  destroy() {
    this.tabContentEl = null;
    this.activeIndex = 0;
    super.destroy();
  }
};
var ContainerTabHWidget = class extends BaseContainerTabWidget {
  getType() {
    return "container-tab-h";
  }
};
var ContainerTabVWidget = class extends BaseContainerTabWidget {
  getType() {
    return "container-tab-v";
  }
};

// src/widgets/built-in/Backlinks.ts
var BacklinksWidget = class extends BaseWidget {
  getType() {
    return "backlinks";
  }
  async renderContent(container, config) {
    const app = window.app;
    const activeFile = app.workspace.getActiveFile();
    if (!activeFile) {
      container.createEl("div", { cls: "xyw-empty", text: "No active file" });
      return;
    }
    const resolvedLinks = app.metadataCache.resolvedLinks ?? {};
    const backlinkFiles = [];
    for (const [path, links] of Object.entries(resolvedLinks)) {
      if (links[activeFile.path]) {
        const f = app.vault.getAbstractFileByPath(path);
        if (f)
          backlinkFiles.push(f);
      }
    }
    let filtered = applyFilters(backlinkFiles, config.filters);
    container.addClass("xyw-recent-files");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-backlinks") });
    if (!filtered.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    const list = container.createEl("ul", { cls: "xyw-file-list" });
    for (const f of filtered) {
      const item = list.createEl("li", { cls: "xyw-file-item", text: f.path });
      item.addEventListener("click", () => {
        app.workspace.getLeaf(false).openFile(f);
      });
    }
  }
};

// src/widgets/built-in/RandomNote.ts
var RandomNoteWidget = class extends BaseWidget {
  getType() {
    return "random-note";
  }
  async renderContent(container, config) {
    const app = window.app;
    const files = app.vault.getMarkdownFiles();
    if (!files.length) {
      container.createEl("div", { cls: "xyw-empty", text: t("msg-no-data") });
      return;
    }
    container.addClass("xyw-recent-files");
    container.createEl("div", { cls: "xyw-card-title", text: config.title || t("type-random-note") });
    const randomFile = files[Math.floor(Math.random() * files.length)];
    const item = container.createEl("div", { cls: "xyw-file-item", text: randomFile.name });
    item.addEventListener("click", () => {
      app.workspace.getLeaf(false).openFile(randomFile);
    });
  }
};

// src/modals/ChildEditorModal.ts
var import_obsidian = require("obsidian");

// src/modals/_shared.ts
var CONTAINER_TYPES = /* @__PURE__ */ new Set(["container-row", "container-col", "container-tab-h", "container-tab-v"]);
var LEAF_TYPES = /* @__PURE__ */ new Set(["stats-card", "recent-files", "tag-cloud", "dv-table", "dv-list", "backlinks", "random-note"]);
function isContainerType(type) {
  return CONTAINER_TYPES.has(type);
}
function isLeafType(type) {
  return LEAF_TYPES.has(type);
}

// src/modals/ChildEditorModal.ts
var ChildEditorModal = class extends import_obsidian.Modal {
  constructor(app, existing) {
    super(app);
    this.existing = existing;
    this.result = null;
    this.resolve = null;
  }
  async openAndGet() {
    return new Promise((resolve) => {
      this.resolve = resolve;
      this.open();
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("xyw-editor-modal");
    let name = this.existing?.name ?? "";
    let type = this.existing?.type ?? "stats-card";
    let settings = this.existing?.settings ? { ...this.existing.settings } : {};
    let children = this.existing?.children ? JSON.parse(JSON.stringify(this.existing.children)) : [];
    const extra = {
      style: this.existing?.style ? JSON.parse(JSON.stringify(this.existing.style)) : void 0,
      filters: this.existing?.filters ? JSON.parse(JSON.stringify(this.existing.filters)) : []
    };
    this.settingsContainerEl = contentEl.createEl("div");
    const renderSettingsWithState = () => {
      this.renderSettings(type, settings, name, (v) => {
        name = v;
      }, (v) => {
        type = v;
        settings = {};
        const meta = getWidgetMeta(type);
        if (meta) {
          for (const field of meta.settingSchema) {
            settings[field.key] = field.defaultValue;
          }
        }
        if (!isContainerType(type))
          children = [];
        renderSettingsWithState();
      }, extra);
    };
    renderSettingsWithState();
    this.styleContainerEl = contentEl.createEl("div");
    this.renderTitleStyle(extra);
    this.contentStyleContainerEl = contentEl.createEl("div");
    this.renderContentStyle(extra);
    this.filterContainerEl = contentEl.createEl("div");
    this.renderFilterSection(extra);
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText(t("btn-save")).setCta().onClick(() => {
      if (!name.trim()) {
        new import_obsidian.Notice("Name is required");
        return;
      }
      this.result = { name: name.trim(), type, settings };
      if (isContainerType(type))
        this.result.children = children;
      if (extra.style && Object.keys(extra.style).length > 0)
        this.result.style = extra.style;
      if (extra.filters.length > 0)
        this.result.filters = extra.filters;
      this.close();
    })).addButton((btn) => btn.setButtonText(t("btn-cancel")).onClick(() => this.close()));
  }
  renderSettings(type, settings, name, setName, onTypeChange, extra) {
    this.settingsContainerEl.empty();
    this.settingsContainerEl.createEl("h3", { text: t("label-config") });
    const card = this.settingsContainerEl.createEl("div", { cls: "xyw-config-card" });
    new import_obsidian.Setting(card).setName(t("label-name")).addText((tc) => tc.setValue(name).onChange((v) => {
      setName(v);
    }));
    new import_obsidian.Setting(card).setName(t("label-type")).addDropdown((dd) => {
      for (const m of getAllWidgetMetas()) {
        if (isLeafType(m.type)) {
          dd.addOption(m.type, t(`type-${m.type}`));
        }
      }
      dd.setValue(type);
      dd.onChange((v) => {
        onTypeChange(v);
      });
    });
    const meta = getWidgetMeta(type);
    if (meta) {
      for (const field of meta.settingSchema) {
        const setting = new import_obsidian.Setting(card).setName(t(field.labelKey));
        const currentVal = settings[field.key] ?? field.defaultValue;
        switch (field.type) {
          case "text":
            setting.addText((tc) => tc.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
              settings[field.key] = v;
            }));
            break;
          case "number":
            setting.addText((t3) => {
              t3.setPlaceholder(field.placeholder ?? "0");
              t3.setValue(String(currentVal));
              t3.inputEl.type = "number";
              t3.onChange((v) => {
                settings[field.key] = Number(v) || 0;
              });
            });
            break;
          case "textarea":
            setting.addTextArea((ta) => ta.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
              settings[field.key] = v;
            }));
            break;
          case "select":
            if (field.options) {
              const opts = field.options;
              setting.addDropdown((dd) => {
                for (const opt of opts)
                  dd.addOption(opt.value, opt.label);
                dd.setValue(String(currentVal));
                dd.onChange((v) => {
                  settings[field.key] = v;
                });
              });
            }
            break;
        }
      }
    }
    this.renderSizeSetting(card, t("style-width"), extra, "width");
    this.renderSizeSetting(card, t("style-height"), extra, "height");
  }
  renderTitleStyle(extra) {
    this.styleContainerEl.empty();
    this.styleContainerEl.createEl("h3", { text: t("style-title") });
    const card = this.styleContainerEl.createEl("div", { cls: "xyw-style-section" });
    new import_obsidian.Setting(card).setName(t("style-title-align")).addDropdown((dd) => {
      dd.addOption("left", t("style-align-left"));
      dd.addOption("center", t("style-align-center"));
      dd.addOption("right", t("style-align-right"));
      dd.setValue(extra.style?.title?.align ?? "left");
      dd.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.title)
          extra.style.title = {};
        extra.style.title.align = v;
      });
    });
    new import_obsidian.Setting(card).setName(t("style-title-color")).addText((tc) => {
      tc.inputEl.type = "color";
      tc.setValue(extra.style?.title?.color ?? "").onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.title)
          extra.style.title = {};
        extra.style.title.color = v;
      });
    });
    new import_obsidian.Setting(card).setName(t("style-title-bg")).addText((tc) => {
      tc.inputEl.type = "color";
      tc.setValue(extra.style?.title?.bgColor ?? "").onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.title)
          extra.style.title = {};
        extra.style.title.bgColor = v;
      });
    });
    new import_obsidian.Setting(card).setName(t("style-title-size")).addText((tc) => {
      tc.inputEl.type = "number";
      tc.inputEl.placeholder = "14";
      tc.setValue(extra.style?.title?.fontSize?.replace(/px$/, "") ?? "");
      tc.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.title)
          extra.style.title = {};
        extra.style.title.fontSize = v ? `${v}px` : "";
      });
    }).addDropdown((dd) => {
      dd.addOption("px", "px");
      dd.setValue("px");
    });
    new import_obsidian.Setting(card).setName(t("style-title-weight")).addDropdown((dd) => {
      dd.addOption("", t("weight-default"));
      dd.addOption("normal", "normal");
      dd.addOption("bold", "bold");
      for (let i = 100; i <= 900; i += 100)
        dd.addOption(String(i), String(i));
      dd.setValue(extra.style?.title?.fontWeight ?? "");
      dd.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.title)
          extra.style.title = {};
        extra.style.title.fontWeight = v || void 0;
      });
    });
  }
  renderContentStyle(extra) {
    this.contentStyleContainerEl.empty();
    this.contentStyleContainerEl.createEl("h3", { text: t("style-content") });
    const card = this.contentStyleContainerEl.createEl("div", { cls: "xyw-style-section" });
    new import_obsidian.Setting(card).setName(t("style-content-align")).addDropdown((dd) => {
      dd.addOption("left", t("style-align-left"));
      dd.addOption("center", t("style-align-center"));
      dd.addOption("right", t("style-align-right"));
      dd.setValue(extra.style?.content?.align ?? "left");
      dd.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.content)
          extra.style.content = {};
        extra.style.content.align = v;
      });
    });
    new import_obsidian.Setting(card).setName(t("style-content-color")).addText((tc) => {
      tc.inputEl.type = "color";
      tc.setValue(extra.style?.content?.color ?? "").onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.content)
          extra.style.content = {};
        extra.style.content.color = v;
      });
    });
    new import_obsidian.Setting(card).setName(t("style-content-size")).addText((tc) => {
      tc.inputEl.type = "number";
      tc.inputEl.placeholder = "13";
      tc.setValue(extra.style?.content?.fontSize?.replace(/px$/, "") ?? "");
      tc.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.content)
          extra.style.content = {};
        extra.style.content.fontSize = v ? `${v}px` : "";
      });
    }).addDropdown((dd) => {
      dd.addOption("px", "px");
      dd.setValue("px");
    });
    new import_obsidian.Setting(card).setName(t("style-content-weight")).addDropdown((dd) => {
      dd.addOption("", t("weight-default"));
      dd.addOption("normal", "normal");
      dd.addOption("bold", "bold");
      for (let i = 100; i <= 900; i += 100)
        dd.addOption(String(i), String(i));
      dd.setValue(extra.style?.content?.fontWeight ?? "");
      dd.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (!extra.style.content)
          extra.style.content = {};
        extra.style.content.fontWeight = v || void 0;
      });
    });
    new import_obsidian.Setting(card).setName(t("style-border-color")).addText((tc) => {
      tc.inputEl.type = "color";
      tc.setValue(extra.style?.borderColor ?? "").onChange((v) => {
        if (!extra.style)
          extra.style = {};
        extra.style.borderColor = v;
      });
    });
  }
  parseSizeValue(val) {
    if (!val)
      return { num: "", unit: "px" };
    const match = val.match(/^([\d.]+)\s*(px|%|em|rem|vw|vh|auto)?$/);
    if (!match)
      return { num: val, unit: "" };
    if (match[2] === "auto")
      return { num: "", unit: "auto" };
    return { num: match[1], unit: match[2] || "px" };
  }
  renderSizeSetting(card, label, extra, prop) {
    const parsed = this.parseSizeValue(extra.style?.[prop]);
    let textComp;
    new import_obsidian.Setting(card).setName(label).addText((tc) => {
      textComp = tc;
      tc.inputEl.type = "number";
      tc.inputEl.placeholder = "auto";
      tc.setValue(parsed.num);
      tc.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        const cur = extra.style[prop] || "";
        const unit = cur.replace(/^[\d.]+/, "") || "px";
        extra.style[prop] = v ? `${v}${unit}` : "";
      });
      if (parsed.unit === "auto")
        tc.inputEl.disabled = true;
    }).addDropdown((dd) => {
      const units = ["px", "%", "em", "rem", "vw", "vh", "auto"];
      for (const u of units)
        dd.addOption(u, u);
      dd.setValue(parsed.unit);
      dd.onChange((v) => {
        if (!extra.style)
          extra.style = {};
        if (v === "auto") {
          extra.style[prop] = "auto";
          textComp.inputEl.disabled = true;
        } else {
          textComp.inputEl.disabled = false;
          extra.style[prop] = textComp.inputEl.value ? `${textComp.inputEl.value}${v}` : "";
        }
      });
    });
  }
  renderFilterSection(extra) {
    this.filterContainerEl.empty();
    this.filterContainerEl.createEl("h3", { text: t("filter-title") });
    const card = this.filterContainerEl.createEl("div", { cls: "xyw-filter-section" });
    const addBtn = card.createEl("button", { cls: "xyw-filter-add-btn" });
    addBtn.textContent = "+ " + t("filter-add");
    addBtn.addEventListener("click", () => {
      extra.filters.push({ source: "fileprop", field: "name", operator: "contains", value: "", logic: "and" });
      this.renderFilterRows(card, extra.filters);
    });
    this.renderFilterRows(card, extra.filters);
  }
  renderFilterRows(container, filters) {
    container.findAll(".xyw-filter-row").forEach((el) => el.remove());
    for (let i = 0; i < filters.length; i++) {
      const row = container.createEl("div", { cls: "xyw-filter-row" });
      const rule = filters[i];
      if (i > 0) {
        const logicSelect = row.createEl("select", { cls: "xyw-filter-logic dropdown" });
        logicSelect.createEl("option", { value: "and", text: "AND" });
        logicSelect.createEl("option", { value: "or", text: "OR" });
        logicSelect.value = rule.logic;
        logicSelect.addEventListener("change", () => {
          rule.logic = logicSelect.value;
        });
      }
      const sourceSelect = row.createEl("select", { cls: "xyw-filter-source dropdown" });
      sourceSelect.createEl("option", { value: "fileprop", text: t("filter-source-fileprop") });
      sourceSelect.createEl("option", { value: "yaml", text: t("filter-source-yaml") });
      sourceSelect.value = rule.source;
      sourceSelect.addEventListener("change", () => {
        rule.source = sourceSelect.value;
        if (rule.source === "fileprop") {
          rule.field = fieldSelect.value;
          fieldSelect.style.display = "";
          fieldInput.style.display = "none";
        } else {
          rule.field = fieldInput.value || "";
          fieldSelect.style.display = "none";
          fieldInput.style.display = "";
        }
      });
      const fieldContainer = row.createEl("span", { cls: "xyw-filter-field" });
      const fieldSelect = fieldContainer.createEl("select", { cls: "dropdown" });
      const filePropFields = ["name", "path", "ctime", "mtime", "size"];
      for (const fp of filePropFields) {
        fieldSelect.createEl("option", { value: fp, text: fp });
      }
      fieldSelect.value = rule.source === "fileprop" ? rule.field : "name";
      fieldSelect.addEventListener("change", () => {
        rule.field = fieldSelect.value;
      });
      const fieldInput = fieldContainer.createEl("input");
      fieldInput.placeholder = "field name";
      fieldInput.value = rule.source === "yaml" ? rule.field : "";
      fieldInput.addEventListener("change", () => {
        rule.field = fieldInput.value;
      });
      fieldInput.addEventListener("blur", () => {
        rule.field = fieldInput.value;
      });
      const updateFieldVisibility = () => {
        if (rule.source === "fileprop") {
          fieldSelect.style.display = "";
          fieldInput.style.display = "none";
        } else {
          fieldSelect.style.display = "none";
          fieldInput.style.display = "";
        }
      };
      updateFieldVisibility();
      const opSelect = row.createEl("select", { cls: "xyw-filter-operator dropdown" });
      const ops = ["contains", "not_contains", "equals", "not_equals", "gt", "lt"];
      for (const op of ops) {
        opSelect.createEl("option", { value: op, text: t(`filter-op-${op}`) });
      }
      opSelect.value = rule.operator;
      opSelect.addEventListener("change", () => {
        rule.operator = opSelect.value;
      });
      const valueInput = row.createEl("input", { cls: "xyw-filter-value" });
      valueInput.value = rule.value;
      valueInput.addEventListener("change", () => {
        rule.value = valueInput.value;
      });
      const delBtn = row.createEl("button", { cls: "xyw-filter-del" });
      delBtn.textContent = "\xD7";
      delBtn.addEventListener("click", () => {
        filters.splice(i, 1);
        container.querySelectorAll(".xyw-filter-row").forEach((el) => el.remove());
        this.renderFilterRows(container, filters);
      });
    }
  }
  onClose() {
    this.contentEl.empty();
    if (this.resolve)
      this.resolve(this.result);
  }
};

// src/modals/WidgetEditorModal.ts
var import_obsidian2 = require("obsidian");
var WidgetEditorModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, store, editId, onSaved) {
    super(app);
    this.plugin = plugin;
    this.store = store;
    this.editId = editId;
    this.onSaved = onSaved;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("xyw-editor-modal");
    const existing = this.editId ? this.store.getWidget(this.editId) : null;
    const isNew = !existing;
    let name = existing?.name ?? "";
    let type = existing?.type ?? "container-row";
    let children = existing?.children ? JSON.parse(JSON.stringify(existing.children)) : [];
    new import_obsidian2.Setting(contentEl).setName(t("label-name")).addText((tc) => tc.setValue(name).onChange((v) => {
      name = v;
    }));
    const dynamicSectionEl = contentEl.createEl("div");
    let settings = existing?.settings ? { ...existing.settings } : {};
    const renderSection = () => {
      this.renderDynamicSection(dynamicSectionEl, type, children, settings, (v) => {
        type = v;
        const meta = getWidgetMeta(type);
        settings = {};
        if (meta) {
          for (const field of meta.settingSchema) {
            settings[field.key] = field.defaultValue;
          }
        }
        if (!isContainerType(type))
          children = [];
        renderSection();
      });
    };
    renderSection();
    const bottomRow = contentEl.createEl("div", { cls: "xyw-bottom-row" });
    new import_obsidian2.ButtonComponent(bottomRow).setButtonText(t("btn-add-child")).setCta().onClick(async () => {
      const modal = new ChildEditorModal(this.app, null);
      const result = await modal.openAndGet();
      if (result) {
        children.push(result);
        renderSection();
      }
    });
    const rightGroup = bottomRow.createEl("div", { cls: "xyw-bottom-right" });
    new import_obsidian2.ButtonComponent(rightGroup).setButtonText(t("btn-save")).setCta().onClick(async () => {
      if (!name.trim()) {
        new import_obsidian2.Notice("Name is required");
        return;
      }
      const data = { name: name.trim(), type, settings };
      if (isContainerType(type))
        data.children = children;
      if (isNew) {
        const saved = await this.store.addWidget(data);
        new import_obsidian2.Notice(t("btn-save"));
        this.onSaved(saved);
      } else {
        await this.store.updateWidget(this.editId, data);
        new import_obsidian2.Notice(t("btn-save"));
        this.onSaved();
      }
      this.close();
    });
    new import_obsidian2.ButtonComponent(rightGroup).setButtonText(t("btn-cancel")).onClick(() => this.close());
  }
  renderDynamicSection(container, type, children, settings, onTypeChange) {
    container.empty();
    if (!isContainerType(type)) {
      const meta = getWidgetMeta(type);
      if (meta && meta.settingSchema.length > 0) {
        container.createEl("h3", { text: t("label-config") });
        for (const field of meta.settingSchema) {
          const setting = new import_obsidian2.Setting(container).setName(t(field.labelKey));
          const currentVal = settings[field.key] ?? field.defaultValue;
          switch (field.type) {
            case "text":
              setting.addText((tc) => tc.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
                settings[field.key] = v;
              }));
              break;
            case "number":
              setting.addText((t3) => {
                t3.setPlaceholder(field.placeholder ?? "0");
                t3.setValue(String(currentVal));
                t3.inputEl.type = "number";
                t3.onChange((v) => {
                  settings[field.key] = Number(v) || 0;
                });
              });
              break;
            case "textarea":
              setting.addTextArea((ta) => ta.setPlaceholder(field.placeholder ?? "").setValue(String(currentVal)).onChange((v) => {
                settings[field.key] = v;
              }));
              break;
            case "select":
              if (field.options) {
                const opts = field.options;
                setting.addDropdown((dd) => {
                  for (const opt of opts)
                    dd.addOption(opt.value, opt.label);
                  dd.setValue(String(currentVal));
                  dd.onChange((v) => {
                    settings[field.key] = v;
                  });
                });
              }
              break;
          }
        }
      }
      return;
    }
    const headerRow = container.createEl("div", { cls: "xyw-section-header" });
    headerRow.createEl("h3", { text: t("label-widget-list") });
    new import_obsidian2.Setting(headerRow).setName(t("label-layout-type")).addDropdown((dd) => {
      for (const m of getAllWidgetMetas()) {
        if (isContainerType(m.type)) {
          dd.addOption(m.type, t(`type-${m.type}`));
        }
      }
      dd.setValue(type);
      dd.onChange((v) => {
        onTypeChange?.(v);
      });
    });
    const listEl = container.createEl("div", { cls: "xyw-child-list" });
    const emptyEl = container.createEl("p", { cls: "xyw-empty-state", text: t("msg-no-children") });
    const refreshList = () => {
      listEl.empty();
      emptyEl.style.display = children.length ? "none" : "";
      for (let i = 0; i < children.length; i++) {
        this.renderChildCard(listEl, children, i, refreshList);
      }
    };
    refreshList();
  }
  renderChildCard(listEl, children, index, onRefresh) {
    const child = children[index];
    const card = listEl.createEl("div", { cls: "xyw-child-card-simple" });
    card.draggable = true;
    card.addEventListener("dragstart", (e) => {
      e.dataTransfer?.setData("text/plain", String(index));
      card.addClass("xyw-dragging");
    });
    card.addEventListener("dragend", () => {
      card.removeClass("xyw-dragging");
      listEl.querySelectorAll(".drag-over").forEach((el) => el.removeClass("drag-over"));
    });
    card.addEventListener("dragover", (e) => {
      e.preventDefault();
      card.addClass("drag-over");
    });
    card.addEventListener("dragleave", () => {
      card.removeClass("drag-over");
    });
    card.addEventListener("drop", (e) => {
      e.preventDefault();
      card.removeClass("drag-over");
      const from = parseInt(e.dataTransfer?.getData("text/plain") ?? "-1");
      if (from >= 0 && from !== index) {
        const [item] = children.splice(from, 1);
        const to = from < index ? index - 1 : index;
        children.splice(to, 0, item);
        onRefresh();
      }
    });
    card.createEl("span", {
      cls: "xyw-child-label-simple",
      text: `${index + 1}. ${child.name} (${t(`type-${child.type}`)})`
    });
    const acts = card.createEl("div", { cls: "xyw-child-actions-simple" });
    new import_obsidian2.ButtonComponent(acts).setIcon("copy").setTooltip("Duplicate").onClick(() => {
      const copy = JSON.parse(JSON.stringify(children[index]));
      children.splice(index + 1, 0, copy);
      onRefresh();
    });
    new import_obsidian2.ButtonComponent(acts).setIcon("pencil").setTooltip(t("btn-edit")).onClick(async () => {
      const modal = new ChildEditorModal(this.app, children[index]);
      const result = await modal.openAndGet();
      if (result) {
        children[index] = result;
        onRefresh();
      }
    });
    new import_obsidian2.ButtonComponent(acts).setIcon("trash-2").setTooltip(t("btn-delete")).onClick(() => {
      children.splice(index, 1);
      onRefresh();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/renderer/CodeBlockRenderer.ts
var import_obsidian3 = require("obsidian");
var CodeBlockRenderer = class {
  constructor(store, plugin) {
    this.activeInstances = /* @__PURE__ */ new Set();
    this.cleanupFns = [];
    this.store = store;
    this.plugin = plugin;
    this.setupAutoRefresh();
  }
  setupAutoRefresh() {
    const refreshAll = () => {
      for (const widget of this.activeInstances) {
        widget.refresh();
      }
    };
    const vault = this.plugin.app.vault;
    const events = [
      vault.on("modify", refreshAll),
      vault.on("delete", refreshAll),
      vault.on("create", refreshAll)
    ];
    this.cleanupFns = events.map((evt) => () => vault.offref(evt));
  }
  destroy() {
    for (const cleanup of this.cleanupFns)
      cleanup();
    for (const widget of this.activeInstances)
      widget.destroy();
    this.activeInstances.clear();
    this.cleanupFns = [];
  }
  async render(source, container) {
    container.empty();
    container.addClass("xyw-block");
    let data;
    try {
      data = this.parseSource(source);
    } catch {
      container.createEl("div", { cls: "xyw-error", text: "Invalid widget config" });
      return;
    }
    const def = this.store.getWidget(data.id);
    if (!def) {
      container.createEl("div", { cls: "xyw-error", text: `Widget "${data.id}" not found. Create it in settings first.` });
      return;
    }
    const widget = createWidget(def.type);
    if (!widget) {
      container.createEl("div", { cls: "xyw-error", text: `Unknown widget type: ${def.type}` });
      return;
    }
    try {
      const mergedSettings = { ...def.settings };
      if (data.settings) {
        Object.assign(mergedSettings, data.settings);
      }
      await widget.render(container, {
        type: def.type,
        title: data.title || def.name,
        settings: mergedSettings,
        children: def.children,
        style: def.style,
        filters: def.filters
      });
      this.activeInstances.add(widget);
    } catch (e) {
      container.empty();
      const message = e instanceof Error ? e.message : String(e);
      container.createEl("div", { cls: "xyw-error", text: `Render error: ${message}` });
    }
    const editBtn = container.createEl("button", { cls: "xyw-edit-overlay" });
    (0, import_obsidian3.setIcon)(editBtn, "pencil");
    editBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      new WidgetEditorModal(this.plugin.app, this.plugin, this.store, data.id, () => {
        this.render(source, container);
      }).open();
    });
  }
  parseSource(source) {
    const lines = source.trim().split("\n");
    const data = {};
    for (const line of lines) {
      const trimmed = line.trim();
      const colonIdx = trimmed.indexOf(":");
      if (colonIdx < 0)
        continue;
      const key = trimmed.slice(0, colonIdx).trim();
      const value = trimmed.slice(colonIdx + 1).trim();
      if (key && value) {
        data[key] = value;
      }
    }
    if (!data.id) {
      throw new Error("Missing id");
    }
    const result = { id: data.id };
    if (data.title)
      result.title = data.title;
    const inlineSettings = {};
    for (const [key, value] of Object.entries(data)) {
      if (key.startsWith("settings.")) {
        inlineSettings[key.slice(9)] = value;
      }
    }
    if (Object.keys(inlineSettings).length > 0)
      result.settings = inlineSettings;
    return result;
  }
};

// src/ui/WidgetPickerModal.ts
var import_obsidian4 = require("obsidian");
var WidgetPickerModal = class extends import_obsidian4.Modal {
  constructor(app, store, onSelect) {
    super(app);
    this.store = store;
    this.onSelect = onSelect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("xyw-picker-modal");
    contentEl.createEl("h2", { text: t("title-pick-widget") });
    const widgets = this.store.getWidgets();
    if (!widgets.length) {
      contentEl.createEl("p", { text: t("label-no-widgets") });
      return;
    }
    const list = contentEl.createEl("div", { cls: "xyw-picker-list" });
    for (const w of widgets) {
      const item = list.createEl("div", { cls: "xyw-picker-item" });
      item.createEl("span", { cls: "xyw-picker-name", text: w.name });
      item.createEl("span", { cls: "xyw-picker-type", text: t(`type-${w.type}`) });
      item.createEl("span", { cls: "xyw-picker-id", text: w.id });
      item.addEventListener("click", () => {
        this.onSelect(w.id);
        this.close();
      });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian5 = require("obsidian");

// src/utils/ReferenceScanner.ts
async function scanWidgetReferences(app, widgetId) {
  const files = app.vault.getMarkdownFiles();
  const results = [];
  const regex = /```xiaoyuanwidget[\s\S]*?id:\s*(\S+)[\s\S]*?```/g;
  for (const file of files) {
    const content = await app.vault.read(file);
    regex.lastIndex = 0;
    let match;
    while ((match = regex.exec(content)) !== null) {
      if (match[1] === widgetId) {
        results.push({ filePath: file.path, fileName: file.name });
      }
    }
  }
  return results;
}

// src/settings.ts
var WidgetSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin, store) {
    super(app, plugin);
    this.plugin = plugin;
    this.store = store;
    this.filterText = "";
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: t("settings-widget-mgr") });
    new import_obsidian5.Setting(containerEl).setDesc(t("codeblock-hint"));
    new import_obsidian5.Setting(containerEl).addButton((btn) => btn.setButtonText(t("btn-new-widget")).setCta().onClick(() => {
      new WidgetEditorModal(this.app, this.plugin, this.store, null, () => this.display()).open();
    })).addButton((btn) => btn.setButtonText(t("btn-export")).onClick(() => {
      const data = this.store.exportWidgets();
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = "xiaoyuan-widgets.json";
      a.click();
      URL.revokeObjectURL(a.href);
    })).addButton((btn) => btn.setButtonText(t("btn-import")).onClick(() => {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = ".json";
      input.onchange = async () => {
        const file = input.files?.[0];
        if (!file)
          return;
        try {
          const text = await file.text();
          const data = JSON.parse(text);
          const arr = Array.isArray(data) ? data : data.widgets ?? [];
          if (!arr.length) {
            new import_obsidian5.Notice("No valid widgets found.");
            return;
          }
          const count = await this.store.importWidgets(arr);
          new import_obsidian5.Notice(t2("msg-import-success", { n: String(count) }));
          this.display();
        } catch (e) {
          new import_obsidian5.Notice("Import failed: " + e.message);
        }
      };
      input.click();
    }));
    new import_obsidian5.Setting(containerEl).addSearch((cb) => cb.setPlaceholder("Search widgets...").setValue(this.filterText).onChange((v) => {
      this.filterText = v.toLowerCase();
      this.display();
    }));
    let widgets = this.store.getWidgets().filter((w) => isContainerType(w.type));
    if (this.filterText) {
      widgets = widgets.filter(
        (w) => w.name.toLowerCase().includes(this.filterText) || w.id.toLowerCase().includes(this.filterText) || t(`type-${w.type}`).toLowerCase().includes(this.filterText)
      );
    }
    if (!widgets.length) {
      containerEl.createEl("p", { cls: "xyw-empty-state", text: this.filterText ? "No matching widgets." : t("label-no-widgets") });
      return;
    }
    const list = containerEl.createEl("div", { cls: "xyw-widget-list" });
    for (const w of widgets) {
      const item = list.createEl("div", { cls: "xyw-widget-card" });
      const info = item.createEl("div", { cls: "xyw-widget-info" });
      const parts = [t(`type-${w.type}`), w.id];
      if (w.children?.length)
        parts.push(`[${w.children.length}]`);
      info.createEl("div", { cls: "xyw-widget-name", text: w.name });
      info.createEl("div", { cls: "xyw-widget-meta", text: parts.join(" \xB7 ") });
      const actions = item.createEl("div", { cls: "xyw-widget-actions" });
      new import_obsidian5.ButtonComponent(actions).setIcon("clipboard-copy").setTooltip("Copy code block").onClick(() => {
        navigator.clipboard.writeText(`\`\`\`xiaoyuanwidget
id: ${w.id}
\`\`\``).then(() => new import_obsidian5.Notice(t("msg-copied")));
      });
      new import_obsidian5.ButtonComponent(actions).setIcon("search").setTooltip(t("label-find-references")).onClick(async () => {
        const refs = await scanWidgetReferences(this.app, w.id);
        const refCount = refs.length;
        if (!refCount) {
          new import_obsidian5.Notice(t("label-no-widgets"));
          return;
        }
        const modal = new import_obsidian5.Modal(this.app);
        modal.contentEl.createEl("h3", { text: `${t("label-find-references")} \u2014 ${w.name}` });
        const list2 = modal.contentEl.createEl("div", { cls: "xyw-widget-list" });
        for (const ref of refs) {
          list2.createEl("div", { cls: "xyw-widget-card", text: ref.filePath });
        }
        modal.open();
      });
      new import_obsidian5.ButtonComponent(actions).setIcon("pencil").setTooltip(t("btn-edit")).onClick(() => {
        new WidgetEditorModal(this.app, this.plugin, this.store, w.id, () => this.display()).open();
      });
      new import_obsidian5.ButtonComponent(actions).setIcon("trash-2").setTooltip(t("btn-delete")).onClick(async () => {
        if (confirm(t2("msg-confirm-delete", { name: w.name }))) {
          await this.store.deleteWidget(w.id);
          this.display();
        }
      });
    }
  }
};

// src/main.ts
var WidgetPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    const lang = getLang();
    setLang(lang);
    this.store = new WidgetStore(
      () => this.loadData(),
      (data) => this.saveData(data)
    );
    this.renderer = new CodeBlockRenderer(this.store, this);
    this.registerWidgetTypes();
    this.registerCodeBlockProcessor();
    this.registerContextMenu();
    this.registerCommands();
    this.registerSettingTab();
  }
  onunload() {
    this.renderer.destroy();
  }
  registerWidgetTypes() {
    const metas = [
      {
        type: "stats-card",
        defaultTitle: t("type-stats-card"),
        description: "Display vault statistics as a card",
        settingSchema: [
          {
            key: "dimension",
            labelKey: "config-dimension",
            type: "select",
            defaultValue: "total",
            options: [
              { label: t("stats-total-notes"), value: "total" },
              { label: t("stats-today"), value: "today" },
              { label: t("stats-week"), value: "week" }
            ]
          }
        ]
      },
      {
        type: "recent-files",
        defaultTitle: t("type-recent-files"),
        description: "List recently modified files",
        settingSchema: [
          {
            key: "limit",
            labelKey: "config-limit",
            type: "number",
            defaultValue: 10,
            placeholder: "10"
          },
          {
            key: "excludeFolders",
            labelKey: "config-exclude-folders",
            type: "textarea",
            defaultValue: "",
            placeholder: "folder1/, folder2/"
          }
        ]
      },
      {
        type: "tag-cloud",
        defaultTitle: t("type-tag-cloud"),
        description: "Display tags as a cloud",
        settingSchema: [
          {
            key: "minCount",
            labelKey: "config-min-count",
            type: "number",
            defaultValue: 1,
            placeholder: "1"
          }
        ]
      },
      {
        type: "dv-table",
        defaultTitle: t("type-dv-table"),
        description: "Execute a Dataview query and display as table",
        settingSchema: [
          {
            key: "query",
            labelKey: "config-query",
            type: "textarea",
            defaultValue: "",
            placeholder: 'TABLE file.ctime FROM ""'
          }
        ]
      },
      {
        type: "dv-list",
        defaultTitle: t("type-dv-list"),
        description: "Execute a Dataview query and display as list",
        settingSchema: [
          {
            key: "query",
            labelKey: "config-query",
            type: "textarea",
            defaultValue: "",
            placeholder: 'FROM "projects"'
          }
        ]
      },
      {
        type: "container-row",
        defaultTitle: t("type-container-row"),
        description: "Arrange child widgets in a horizontal row",
        settingSchema: []
      },
      {
        type: "container-col",
        defaultTitle: t("type-container-col"),
        description: "Arrange child widgets in a vertical column",
        settingSchema: []
      },
      {
        type: "container-tab-h",
        defaultTitle: t("type-container-tab-h"),
        description: "Arrange child widgets as horizontal tabs",
        settingSchema: []
      },
      {
        type: "container-tab-v",
        defaultTitle: t("type-container-tab-v"),
        description: "Arrange child widgets as vertical tabs",
        settingSchema: []
      },
      {
        type: "backlinks",
        defaultTitle: t("type-backlinks"),
        description: "Show backlinks for the active file",
        settingSchema: []
      },
      {
        type: "random-note",
        defaultTitle: t("type-random-note"),
        description: "Open a random note",
        settingSchema: []
      }
    ];
    const widgets = [
      { ctor: StatsCardWidget, meta: metas[0] },
      { ctor: RecentFilesWidget, meta: metas[1] },
      { ctor: TagCloudWidget, meta: metas[2] },
      { ctor: DataviewTableWidget, meta: metas[3] },
      { ctor: DataviewListWidget, meta: metas[4] },
      { ctor: ContainerRowWidget, meta: metas[5] },
      { ctor: ContainerColWidget, meta: metas[6] },
      { ctor: ContainerTabHWidget, meta: metas[7] },
      { ctor: ContainerTabVWidget, meta: metas[8] },
      { ctor: BacklinksWidget, meta: metas[9] },
      { ctor: RandomNoteWidget, meta: metas[10] }
    ];
    for (const { ctor, meta } of widgets) {
      registerWidgetType(ctor, meta);
    }
  }
  registerCodeBlockProcessor() {
    this.registerMarkdownCodeBlockProcessor("xiaoyuanwidget", async (source, el, ctx) => {
      await this.renderer.render(source, el);
    });
  }
  registerContextMenu() {
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        let rootSub = null;
        menu.addItem((item) => {
          item.setTitle(t("context-insert-widget"));
          rootSub = item.setSubmenu();
        });
        rootSub.addItem((item) => {
          item.setTitle(t("context-new-widget"));
          item.setIcon("plus");
          item.onClick(() => {
            new WidgetEditorModal(this.app, this, this.store, null, (widget) => {
              if (widget)
                this.insertCodeBlock(editor, widget.id);
            }).open();
          });
        });
        const widgets = this.store.getWidgets().filter((w) => {
          const containerTypes = /* @__PURE__ */ new Set(["container-row", "container-col", "container-tab-h", "container-tab-v"]);
          return containerTypes.has(w.type);
        });
        if (widgets.length === 0) {
          rootSub.addItem((item) => {
            item.setTitle(t("label-no-widgets"));
            item.setDisabled(true);
          });
          return;
        }
        let insertSub = null;
        rootSub.addItem((item) => {
          item.setTitle(t("context-insert-wgt"));
          insertSub = item.setSubmenu();
        });
        const grouped = /* @__PURE__ */ new Map();
        for (const w of widgets) {
          const list = grouped.get(w.type) || [];
          list.push(w);
          grouped.set(w.type, list);
        }
        const typeOrder = getAllWidgetTypes();
        for (const type of typeOrder) {
          const list = grouped.get(type);
          if (!list || list.length === 0)
            continue;
          let typeSub = null;
          insertSub.addItem((item) => {
            item.setTitle(t(`type-${type}`));
            typeSub = item.setSubmenu();
          });
          for (const w of list) {
            typeSub.addItem((item) => {
              item.setTitle(w.name);
              item.onClick(() => {
                this.insertCodeBlock(editor, w.id);
              });
            });
          }
        }
      })
    );
  }
  insertCodeBlock(editor, id) {
    const code = `\`\`\`xiaoyuanwidget
id: ${id}
\`\`\``;
    const cursor = editor.getCursor();
    editor.replaceRange(code, cursor);
    editor.setCursor({
      line: cursor.line + 3,
      ch: 0
    });
  }
  registerCommands() {
    this.addCommand({
      id: "insert-widget",
      name: "Insert widget at cursor",
      editorCallback: (editor, view) => {
        new WidgetPickerModal(this.app, this.store, (id) => {
          this.insertCodeBlock(editor, id);
        }).open();
      }
    });
  }
  registerSettingTab() {
    this.addSettingTab(new WidgetSettingTab(this.app, this, this.store));
  }
};
